### PR TITLE
BREAKING CHANGE: catalogue data model update; cohort details expanded

### PR DESCRIPTION
**Pull request by BrendaHijmans**
creates incompatibility with catalogue app

### CODE REVIEW

**Review by mswertz — COMMENTED** [review]
Accepted:
Resource.externalIdentifiers: ok (ik onderdruk neiging het mooier te maken)
resource.keywords: ok; we zouden hier een 'keywords' en 'keywordsOther' kunnen doen? Want nu kun je er niet systematisch op filteren alleen vrije tekst
resource.inclusionCriteria: ok.
Contact.expertise: ok
Verplaatsen dataCategories, sampleCategories naar CollectionEvent, ok (we verplichten cohorten dan minstens 1 collectionEvent aan te maken, prima).
Cohorts.design ok
Cohors.collectionType: ok naam tweede vind ik weinig specifiek

Bespreken:
resource.releaseTypes + releaseDescription => overlapt met Minerva, proberen gelijk te trekken? Of omlaag duwen naar cohorten?
CollectionEvent.areasOfInterest: dat is toch hetzelfde als dataCategories??? Samenvoegen?
Resource.type opheffen en per subclass beter oplossen?

**Review by mswertz — CHANGES_REQUESTED** [review]
I have issue to understand difference between areasOfInformation and dataCategories. I propose to merge, and use areasOfInformation as dataCategories

**Comment by mswertz** [comment]
Shall we add a section to docs where we document each breaking change and how to deal with them? In this case I suppose there is now automated procedure and actually it is not breaking in strict meaning (data will load, however some data will be ommitted).

**Review by BrendaHijmans — COMMENTED** [review]
data model edits are okay.
app looks okay, but I have not viewed it in the app, just in the code
cannot approve or merge request, because I authored the PR

**Comment by mswertz** [comment]
okay, lets risk it then. If the UX turns out broken we push a fix?

**Review by mswertz — APPROVED** [review]

**Pull request merged**
