### PR TITLE
feat: added tool ontologymanager

### PR DESCRIPTION
**Pull request by YpeZ**
Python tool to manage a server's CatalogueOntologies tables. The tool supports adding terms to ontology tables, deleting terms from a table and update references from one ontology term to another within all databases on the server.

- [x] Method to add term to ontology
- [x] Method to delete term from ontology
- [x] Method to update references to ontology term
- [ ] Implement ci build and release to pypi.org
- [ ] Store changes made and allow restore last modification on server

Additional
- [x] Keep server/database schema in memory
- [x] Create option to modify multiple terms and tables simultaneously
- [x] Create option to add ontology entries by csv/pandas dataframe object
- [x] Add command line interface

### CODE REVIEW

**Comment by erikzwart** [comment]
Difficult to get up and running at this stage, client is not yet published on pip so you need to install manually with the *.whl. The pyclient README does describe this, building the pyclient did not work for me however for some reason.
Also not clear is how the .env should look like, we need to add an example to the README. Had to change the way the module is loaded `from molgenis_emx2_client import Client` did not work `from molgenis import Client`  did work.
Also missed some variables from the .env (after pip install python-dotenv, need to add to requirements), like email (username) and database in the OntologyManager.
I was able to run the demo `demo_ontomanager.py` and add a Country, the update step half worked and resulted in a 404:

b'{"query": "\\n        {\\n          _schema {\\n            tables {\\n              name\\n              externalSchema\\n              inherit\\n              tableType\\n              columns {\\n                name \\n                required\\n                key\\n                columnType \\n                refSchema\\n                refTable\\n              }      \\n            }\\n          }\\n        }"}'

Note: used emx2.dev.molgenis.org to test (CatalogueOntologies and catalogue-demo [TestCohort])

**Comment by erikzwart** [comment]
- we need to add how to use the .env file
- The cli option to add a country: `python3 -m molgenis_ontomanager add Countries --name='Republic of Molgenia', --label='Molgenia'`  results in 'Republic of Molgenia,' see screenshot below (previous attempt is not overwritten) and error below that

image

image

**Comment by erikzwart** [comment]
Using the example from README.md 'In command line as module' are not working correctly if I copy paste them, as seen in previous comment. Need to add some quotes to escape --name='xx'

Update Countries gave error:
image

**Comment by YpeZ** [comment]
> * we need to add how to use the .env file
> 
>     * The cli option to add a country: `python3 -m molgenis_ontomanager add Countries --name='Republic of Molgenia', --label='Molgenia'`  results in 'Republic of Molgenia,' see screenshot below (previous attempt is not overwritten) and error below that
> 
> 
> image
> 
> image

Correct, I removed the comma's in the readme

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
README should have a section on making a virtual env and installing requirements in requirements.txt. python-dotenv==1.0.0 is required for installing molgenis-emx2-ontomanager

requirements.txt cannot be installed, since molgenis-emx2-client~=0.7 does not exist

**Comment by BrendaHijmans** [comment]
Could you add the terms to add/change/delete to the environment variables, so that you only need to change your .env to run the ontology manager on the preferred data?

**Comment by BrendaHijmans** [comment]
can you add a .gitignore for e.g. .env

**Comment by YpeZ** [comment]
@BrendaHijmans  I strongly disagree with adding any more usage instructions that are not essential for using the package, such as working with a .env file.
The README makes it abundantly clear how to import and use the package by supplying the url, username and password.

The user can supply this information in any way they want within their own programs, for example by a .env file, but this is not inherent to the functionality of the package.

**Pull request closed without merging**
