### PR TITLE
fix: empty setting in molgenis_settings  file should remove setting

### LINKED ISSUE #2199: Can not upload molgenis-settings.csv if it contains an empty setting value
**What version of EMX2 are you using (see footer)**
8.151.1

**Describe the bug**
Can not upload molgenis-settings.csv if it contains an empty setting value

**To Reproduce**
1. Create schema
2. Add some settings 
3. Add a setting with an empty value ( or clear an existing value)
4. Download the scheme + data 
5. upload to new schema
6. Upload fails with message "description cannot be null"

**Expected behavior**
Successful upload

### PR DESCRIPTION
**Pull request by mswertz**
closes #2199

### CODE REVIEW

**Review by connoratrug — CHANGES_REQUESTED** [review]
when i create a setting that has a empty value the setting is not added. Expected to setting to be added with a empty value. i.e. empty string should be a valid setting value. ( empty string is not a valid setting key)

**Review by connoratrug — CHANGES_REQUESTED** [review]
when i create a setting that has a empty value the setting is not added. Expected to setting to be added with a empty value. i.e. empty string should be a valid setting value. ( empty string is not a valid setting key)

**Comment by mswertz** [comment]
I am also okay to set with empty value. Will update PR to do so.

**Comment by mswertz** [comment]
Okay, I updated it but I am not sure it is better @connoratrug => considering that settings is a hash map, then most java fans would say you should not store the null values but remove the key.

**Review by connoratrug — APPROVED** [review]

**Pull request merged**
