### PR TITLE
feat: add collection and subcollection count to biobank and network details

### LINKED ISSUE #3663: featdirectory): Split network and biobank page collections count into sub and normal collections.
demo:
- [ ] number of collections is split between collections and subcollections on network page
- [ ] number of collections is split between collections and subcollections on biobank report page

**Is your feature request related to a problem? Please describe.**
The biobank and network details show the total number of collections, while the main page splits this up in the number of collections and the number of sub collections.

**Describe the solution you'd like**
The number is split in number of collections and number of sub collections in the network and biobank details pages.

### PR DESCRIPTION
**Pull request by chinook25**
What are the main changes you did:
-closes #3663 

how to test:
- Go to https://preview-emx2-pr-4032.dev.molgenis.org
- upload bbrmi dataset
- go to directory app
- go to a biobank that has subcollections 
- See that both the collection count and the subcollection count are shown.

- Go to a network that has subcollection 
- See that the collection count is now split into sub and parent collections

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
Logic looks fine, but we need to test with a better test dataset. I asked @dtroelofsprins about that.

I would suggest to put the number of sub collections next to the number of collections with a tool tip explaining the numbers. e.g.:

Collections (10 / 15<sup>(?)</sup> )

When you then click on the <sup>(?)</sup> you should get an explanation of the numbers.

Screenshot 2024-07-15 at 13 52 23

**Comment by esthervanenckevort** [comment]
I looked at the counts for the BBMRI.de network with a copy of the production data that Dieuwke provided and the counts are correctly split up between collections and subcollections. 

However I noticed that withdrawn status for the collections is ignored. I will create a new issue for that.

**Review by dtroelofsprins — APPROVED** [review]
Did a quick functional test. Counts of collections and sub collections both on the biobank as well as the network card are fine.

**Comment by chinook25** [comment]
> Logic looks fine, but we need to test with a better test dataset. I asked @dtroelofsprins about that.
> 
> I would suggest to put the number of sub collections next to the number of collections with a tool tip explaining the numbers. e.g.:
> 
> Collections (10 / 15(?) )
> 
@esthervanenckevort 

What should the explanation look like?  Just something like: 
```
Collections: 10
Subcollections: 15
```

Should this also be applied to the biobankreport (I assume we want it a bit consistent)?

**Comment by esthervanenckevort** [comment]
> > Logic looks fine, but we need to test with a better test dataset. I asked @dtroelofsprins about that.
> > I would suggest to put the number of sub collections next to the number of collections with a tool tip explaining the numbers. e.g.:
> > Collections (10 / 15(?) )
> 
> @esthervanenckevort
> 
> What should the explanation look like? Just something like:
> 
> ```
> Collections: 10
> Subcollections: 15
> ```

Yes
> 
> Should this also be applied to the biobankreport (I assume we want it a bit consistent)?

Yes

> 
> I'll just use a normal tooltip, since I'd rather not make a new component in the old library for just this.

There is already some component for that, tooltips are also used for quality labels for instance.

**Review by esthervanenckevort — APPROVED** [review]

**Review by konstantina-gkp — APPROVED** [review]

**Pull request merged**
