### PR TITLE
fix: loading state of "diagnosis filter" url

### PR DESCRIPTION
**Pull request by konstantina-gkp**
fixes: #3690

What are the main changes you did:
- Adjusted the graphql endpoint for the ontology filter
- Fixed the ontology filter for several diagnosis filters

how to test:
- Apply a diagnosis filter in the directory app
- Copy the url with the diagnosis filter parameter and paste it in a new tab (or refresh the current page)
- The application retrieves the results matching the filter

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
- It doesn't work with this URL:
https://preview-emx2-pr-3696.dev.molgenis.org/directory-demo/directory/#/catalogue?Diagnosisavailable=QzE4LjAsQzE4LjEsQzE4LjIsQzE4LjMsQzE4LjQsQzE4LjUsQzE4LjYsQzE4LjcsQzE4LjgsQzE4LjksQzE4
- Not up to date with master

**Comment by konstantina-gkp** [comment]
- When navigating to a url that contains a single directory filter, the fix works and the application retrieves the matching results. See image below:
diagnosis_filter_state
- What I notice is that the fix does not fully work when several filters are applied. The url works, but the application does not retrieve the results for the matching filter.
- Master was updated today early in the morning and in the afternoon. The new changes were irrelevant to the issue/project.

**Review by dtroelofsprins — COMMENTED** [review]
I've tried several 'single' diagnosis filters, but in all cases copying the URL to a new tab results in "Loading State"....

Tested it with Safari and Chrome

**Review by dtroelofsprins — APPROVED** [review]
Functional test:
- [x] Copying a URL with a single diagnosis filter
- [x] Copying a URL with multiple diagnosis filter options (tested with 2)
- [x] Copying a URL with multiple diagnosis filter options and one other filter (tested with categories)
- [x] Copying a URL with multiple diagnosis filter options and two other filters (tested with categories and material types)

**Review by esthervanenckevort — APPROVED** [review]

**Pull request merged**
