### PR TITLE
fix: subcollection counts on nework and biobank details pages

### LINKED ISSUE #3663: featdirectory): Split network and biobank page collections count into sub and normal collections.
demo:
- [ ] number of collections is split between collections and subcollections on network page
- [ ] number of collections is split between collections and subcollections on biobank report page

**Is your feature request related to a problem? Please describe.**
The biobank and network details show the total number of collections, while the main page splits this up in the number of collections and the number of sub collections.

**Describe the solution you'd like**
The number is split in number of collections and number of sub collections in the network and biobank details pages.

### PR DESCRIPTION
**Pull request by konstantina-gkp**
Konstantina 12-07-2024:
Indeed, I am currently not working on that issue anymore. As discussed before, the directory app needs extensive refactoring for that feature in order to properly implement it. And, the current counts in the front page cannot be applied to the biobank and network report, since they are only specifically implemented for the front page. I think the PR should not be deleted, because it still fixes a part of the problem and if someone else picks it up, they do not need to redo certain parts (e.g., the creation of tabs, popovers, the design and a part of the logic for calculating those counts).

fix: #3663

What are the main changes you did:
- added subcollection count  and a tooltip on the "Collection" tab in network report
- added collection tab with collection, subcollection counts and a tooltip in biobank report
- refactoring

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
The sub collections should not be a separate tab, they only make sense in the context of the collection. Rather than having a separate tab the count that is displayed in the Collections tab should be split up.
E.g. if there are 10 collections with 15 sub collections it should show these numbers behind the title Collections. (10 / 15) Maybe with a tooltip to explain the numbers: "10 collections with 15 sub collections". 

Sorry if this wasn't clear from the issue.

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
I didn't read the Esther's comment before looking at the preview, for me it was good that the tooltip was there, because at first glance the 10/5 was not clear to me what it meant.

Furthermore did some count checks:

- [x] collection/subcollections counts on biobank cards
- [ ] collection/subcollections counts on network cards 

It turns out that collection/subcollection counts on networks cards are not OK. 
GoTo: https://preview-emx2-pr-3839.dev.molgenis.org/DieuwkesTest/directory/#/catalogue

=> click biobank [Acibadem University Biobank](https://preview-emx2-pr-3839.dev.molgenis.org/DieuwkesTest/directory/#/biobank/bbmri-eric:ID:EXT_ACU)
=> Then goto network overview: https://preview-emx2-pr-3839.dev.molgenis.org/DieuwkesTest/directory/#/network/bbmri-eric:networkID:EU_BBMRI-ERIC:networks:COVID19 there are 122/5, but the 122 is the total number of collections and there are 7 subcollections: https://preview-emx2-pr-3844.dev.molgenis.org/DieuwkesTest/tables/#/Collections?_col=id,parent_collection,sub_collections&_order=ASC&_orderBy=parent_collection&_filter=network&network=[{%22id%22:%22bbmri-eric:networkID:EU_BBMRI-ERIC:networks:COVID19%22}]

**Review by dtroelofsprins — COMMENTED** [review]
And maybe it's also good to ask @MaxPostema or @chinook25 to do a technical review

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
The networks details page gives an error when I look at it with the demo set (https://preview-emx2-pr-3839.dev.molgenis.org/directory-demo/directory/#/network/bbmri-eric:networkID:DE_nw_coll1)

`[Error] TypeError: undefined is not an object (evaluating 'b.value.length')
	logError (index-3a10cb7f.js:16:2901)
	handleError (index-3a10cb7f.js:16:2848)
	callWithErrorHandling (index-3a10cb7f.js:16:2190)
	setupStatefulComponent (index-3a10cb7f.js:16:71858)
	setupComponent (index-3a10cb7f.js:16:71518)
	O (index-3a10cb7f.js:16:53894)
	F (index-3a10cb7f.js:16:53720)
	S (index-3a10cb7f.js:16:49763)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	N (index-3a10cb7f.js:16:51595)
	T (index-3a10cb7f.js:16:50662)
	I (index-3a10cb7f.js:16:50454)
	S (index-3a10cb7f.js:16:49729)
	z (index-3a10cb7f.js:16:52804)
	R (index-3a10cb7f.js:16:51963)
	I (index-3a10cb7f.js:16:50481)
	S (index-3a10cb7f.js:16:49729)
	ue (index-3a10cb7f.js:16:54750)
	run (index-3a10cb7f.js:9:1921)
	(anonymous function) (index-3a10cb7f.js:16:55787)
	callWithErrorHandling (index-3a10cb7f.js:16:2167)
	flushJobs (index-3a10cb7f.js:16:4926)`

**Review by chinook25 — CHANGES_REQUESTED** [review]

**Pull request closed without merging**
