### PR TITLE
chore(directory): add asterisks to ontology tables

### PR DESCRIPTION
**Pull request by dtroelofsprins**
What are the main changes you did:
- Added asterisks (*) as codes to AgeRanges, DiseaseTypes, MaterialTypes and SexTypes biobank-directory ontology tables

how to test:
- Go to the preview and check the above mentioned tables and see the * as a record

todo:
- [na] updated docs in case of new feature
- [na] added/updated tests
- [na] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
De regels met een * zouden ook een label moeten hebben en een definitie, zodat het voor de gebruiker duidelijk is.

**Review by esthervanenckevort — DISMISSED** [review]
Label should be: any
Definition should be: Any age range / Any material type / Any sex / Any disease

**Comment by dtroelofsprins** [comment]
When I change the label to Any the issue solved in PR https://github.com/molgenis/molgenis-emx2/pull/3998 is re-introduced. It seems that in this fix not the pk column (=name) of the ontology tables has been used, but the label?!

**Comment by sasurfer** [comment]
I changed the label check from '*' to 'Any'

**Review by sasurfer — APPROVED** [review]
Done some checks and everything works as supposed to.

**Pull request merged**
