### PR TITLE
feat: 3484 Show repeats in variable list

### LINKED ISSUE #3484: When searching for a variable which has repeated measurements, clearer information should be provided on the 'list of variables' tab
Decision: show (+ 12) 

**Is your feature request related to a problem? Please describe.**
When searching for a variable which has repeated measurements, in the 'list of variables' tab, only the first variable is returned. This can leave it confusing for a researcher unfamiliar with the catalogue whether data exists at additional ages, or whether this is the only variable that exists. 

**Describe the solution you'd like**
For me it would be more intuitive if only the stem of the variable was displayed (e.g. "adhd_wave_", rather than "adhd_wave_1"), and potentially an additional element to the right stating 'repeated measurements'.

**Describe alternatives you've considered**
Make no changes and leave it for the researcher to discover this when clicking on the variable.

**Additional context**
Captura de pantalla 2024-03-11 a las 11 35 33 (2)

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #3484

alt styling
see: https://github.com/molgenis/molgenis-emx2/pull/3758
see: https://github.com/molgenis/molgenis-emx2/pull/3759

What are the main changes you did:
-Added the number of repeats ( if any) next to the variable name in the variable list 

how to test:
- explain here what to do to test this (or point to unit tests)

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by timcadman — CHANGES_REQUESTED** [review]
- Is it possible to amend the text wrapping so that "(x repeats") remains together on the same line? See below: "(1" is on the first line, everything else on the second

Captura de pantalla 2024-05-16 a las 10 44 14

what would you like to happend when the text is larger then the max column with , see alternative PR's 

#3758 and #3759

**Comment by connoratrug** [comment]
suggest to first make a design of the desired solution before implementing in code, as some exploring / iterating is needed

**Comment by timcadman** [comment]
This is what I had in mind after the variable ...

Captura de pantalla 2024-05-16 a las 14 37 04

**Comment by connoratrug** [comment]
> This is what I had in mind after the variable ...
> 
> Captura de pantalla 2024-05-16 a las 14 37 04

i tried that it looked a bit messy/ less clear to me, and what does the '+' sign mean in ? , anyway i propose to do the design details in figma ( or other tool ) the whole checkout, commit , PR , build preview , review loop takes a bit to long for design details imo, i'll make some figma options add link to those

**Comment by timcadman** [comment]
Yeah sorry, I don't know how to use figma or much design skills myself. I don't think we should spend much time on this - it is a stop-gap measure to stop people complaining and long-term we might think about a more complete solution. I would suggest to go with option 2 as is.
@mswertz?

**Comment by mswertz** [comment]
> This is what I had in mind after the variable ...
> 
> Captura de pantalla 2024-05-16 a las 14 37 04

Yes that is also what I have in mind :-)

**Pull request closed without merging**
