### PR TITLE
chore(deps): remove graphql-tag

### PR DESCRIPTION
**Pull request by chinook25**
Remove graphql-tag as it offers the same functionality as graphql-request already does. Also make sure that every file using the gql import actually imports it.

### CODE REVIEW

**Review by BrendaHijmans — COMMENTED** [review]
Cohort view in ssr-catalogue is broken, e.g.: https://preview-emx2-pr-3019.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/ABCD
Subcohort view also, e.g.: https://preview-emx2-pr-3019.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/cohorts/ALSPAC/subcohorts/Children

**Review by connoratrug — CHANGES_REQUESTED** [review]
see https://github.com/molgenis/molgenis-emx2/pull/3019#pullrequestreview-1744662496

suggest to add graphql-tag ( much smaller then gql-request) to ssr app , the app only needs the tag part for query loading

**Review by mswertz — APPROVED** [review]

**Review by davidruvolo51 — APPROVED** [review]
All vue applications for the ERNs and the molgenis-viz library work with the new graphql tag.

**Comment by chinook25** [comment]
closing because someone did weird merging stuff to the branch.

**Pull request closed without merging**
