### PR TITLE
feat: update data model for umcg

### PR DESCRIPTION
**Pull request by BrendaHijmans**
Added data items:
CollectionEvents.coreVariables, Subcohorts.comorbidity, Subcohorts.counts, 
Added table: SubcohortCounts

### CODE REVIEW

**Review by connoratrug — CHANGES_REQUESTED** [review]
ssr catalogue needs to be updated

**Comment by connoratrug** [comment]
> Still needs:

> -adding of these data items to UI
> -adding of extra table to pass test 

Are the notes still up to date  ?

**Comment by mswertz** [comment]
[UMCG data model wijzigingen PR](https://trello.com/c/hMLhHDQ3/445-umcg-data-model-wijzigingen-pr)

**Comment by mswertz** [comment]
[#8782 Add more metadata fields to cohorts (for UMCG) [review by CBCH & waiting for ontology lists to implement from CBCH]](https://trello.com/c/bPbBF4fP/365-8782-add-more-metadata-fields-to-cohorts-for-umcg-review-by-cbch-waiting-for-ontology-lists-to-implement-from-cbch)

**Comment by BrendaHijmans** [comment]
new data items are visible in the subcohort view and collection event view.

**Comment by mswertz** [comment]
> ssr catalogue needs to be updated

Can you please do that?

**Review by connoratrug — APPROVED** [review]

**Pull request merged**
