### PR TITLE
fix: fix query builder

### PR DESCRIPTION
**Pull request by connoratrug**
- find tableMetadata by name instead of id
- recursively parse query fields to build gql query fields string
- use generated resource id path for dynamic resource details path

to test: https://preview-emx2-pr-2773.dev.molgenis.org/catalogue-demo/ssr-catalogue/VariableMappings

### CODE REVIEW

**Comment by mswertz** [comment]
I don't understand how it really should work, test showed me this when clicking a variablemapping

Or is this in prep of the 'identifier->name' conversion?

image

**Review by mswertz — CHANGES_REQUESTED** [review]
It might be that I don't understand how to test so then change description and not code but I commented on an issue I encountered

**Comment by connoratrug** [comment]
> It might be that I don't understand how to test so then change description and not code but I commented on an issue I encountered

No i get a different result following the same link , did you test using the CI preview ?

**Comment by connoratrug** [comment]
added simple table view for easy testing https://preview-emx2-pr-2773.dev.molgenis.org/catalogue-demo/ssr-catalogue/tables

**Pull request merged**
