### PR TITLE
fix: limit/offset/where should be applied before json nested joins otherwise queries get slow. closes #3666 closes #3481 closes #3652.

### LINKED ISSUE #3476: Query in networks table runs out of time for data model v 3.12 on dev server, not on data catalogue server
**What version of EMX2 are you using (see footer)**
10.45.1

**Describe the bug**
When loading demo data in the DATA_CATALOGUE data model via the template reader, there is an error when viewing the Networks table. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. Click on + to create a new schema
3. Under template select 'DATA_CATALOGUE', load example data = True
4. wait a while for data to load, finish of loading will not be prompted (see issue: https://github.com/molgenis/molgenis-emx2/issues/3059)
5. refresh page and open newly made schema
6. move to table Networks
7. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #3481: 'Variables' page is very slow to load
**What version of EMX2 are you using (see footer)**
v10.37.1

**Describe the bug**
On the beta catalogue, when clicking the 'variable' button in the top right corner of screen it takes approximately 12 seconds for the variable page to load.

**To Reproduce**
Follow test-plan 1 until step 8:
https://github.com/molgenis/molgenis-emx2/pull/3135/files#diff-87d0d7863e01e079d5bbe8c69f27fc8a36ede2c1faea26e077f7dee7cbc4e32c 

**Expected behavior**
The variable pages loads within a couple of seconds.

**Desktop (please complete the following information):**
 - OS: masOS Sonoma 14.3.1
 - Browser: Chrome 
 - Version 122.0.6261.69

**Additional context**
Connecting via a wireless network at ISGlobal university in Barcelona

### LINKED ISSUE #3652: Cannot view Cohorts table due to time out error
**What version of EMX2 are you using (see footer)**
10.58.0, 10.58.1, also older 10.48.8

**Describe the bug**
I cannot view the Cohorts table due to an error.
image

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Cohorts

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #3666: paging to last record in large tables is very slow.
See for example:
https://emx2.dev.molgenis.org/CatalogueOntologies/tables/#/MedDRA?_page=4446

### PR DESCRIPTION
**Pull request by mswertz**
closes #3652. 
closes #3476

What are the main changes you did:
- made sure filter, limit, offset, order by are applied before json is build

how to test:
- compare speed on this PR vs another PR. See example below

### CODE REVIEW

**Comment by mswertz** [comment]
BEFORE (comparing to JIT to make sure that hasn't anything to do with it)
https://preview-emx2-pr-3704.dev.molgenis.org/CatalogueOntologies/tables/#/MedDRA?_page=4446
image

AFTER
https://preview-emx2-pr-3719.dev.molgenis.org/CatalogueOntologies/tables/#/MedDRA?_page=4446
image

**Comment by mswertz** [comment]
go between page 36 and 37

BEFORE (with jit=off):
https://preview-emx2-pr-3704.dev.molgenis.org/catalogue-demo/ssr-catalogue/ATHLETE/variables?page=36&view=harmonization
image

BEFORE (with jit != off)
https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/ATHLETE/variables?page=37&view=harmonization
image

AFTER:
https://preview-emx2-pr-3719.dev.molgenis.org/catalogue-demo/ssr-catalogue/ATHLETE/variables?page=37&view=harmonization
image

**Review by timcadman — APPROVED** [review]
This is a big speed improvement, nice work :) I wasn't sure how to measure the times precisely as you did, but I can confirm that the PR speeds things up significantly.

**Comment by mswertz** [comment]
Ok, I found a bug myself
image

**Pull request merged**
