### PR TITLE
feat: Allow for networks and partners without logo

### PR DESCRIPTION
**Pull request by connoratrug**
Nieuw view can be seen on: ```/alt-cohorts/:pid```

### CODE REVIEW

**Comment by mswertz** [comment]
I compared 'old' and 'new'. 

Missing from new:
- networks
- link to the organisation/provider (in UMCG that of course is UMCG but is not case for others)
- conditions of use etc (there are already areas for that so might be data)
- design paper
- links to documentation if available

**Comment by connoratrug** [comment]
> I compared 'old' and 'new'.
> 
> Missing from new:
> 
> * networks
> * link to the organisation/provider (in UMCG that of course is UMCG but is not case for others)
> * conditions of use etc (there are already areas for that so might be data)
> * design paper
> * links to documentation if available

networks are in the new nieuw ( logo is required)
 design paper is marker paper ..? 
conditions of use  -> Access conditions

added a block for the docs
added the institution

**Review by mswertz — CHANGES_REQUESTED** [review]
Changes requested:

* I would like to be able to see the network also when no logo is provided.
I would propose a simple link in some heading format would be okay. Or even a 'logo missing' with a link underneath. To stimulate that logos are added.

* I want to be able to click the link to institution. To make it look nice, I recommend to make it change into a link on mouse over?

* I also see the "Available data and samples" box is not yet developed. I think this is currently not modelled on level of cohorts, right? Can you please discuss with data managers? In practice this should be the union of all collectionEvents right?

N.B. outside scope of this pull request: I recommend we also make the Ontology Terms more informative, e.g. by having ability to show its definition either using a (i) icon or by simply having tooltip on mouse over.

**Comment by connoratrug** [comment]
> Changes requested:
> 
> * I would like to be able to see the network also when no logo is provided.
>   I would propose a simple link in some heading format would be okay. Or even a 'logo missing' with a link underneath. To stimulate that logos are added.

maybe have a 'anonymous logo' similar to missing user picture, i would really like to stimulate adding a logo. personally i would suggest keeping it as it is, and actively add de logo's ourselves.  

> * I want to be able to click the link to institution. To make it look nice, I recommend to make it change into a link on mouse over?

Not a fan of on mouse over , i'll add a link and we can update styling if needed

> * I also see the "Available data and samples" box is not yet developed. I think this is currently not modelled on level of cohorts, right? Can you please discuss with data managers? In practice this should be the union of all collectionEvents right?

No it's there, just add data 

> 
> N.B. outside scope of this pull request: I recommend we also make the Ontology Terms more informative, e.g. by having ability to show its definition either using a (i) icon or by simply having tooltip on mouse over.

No sure what you mean by this, suggest to open a story / issue and add a mockup

**Comment by erikzwart** [comment]
For this example I used the cohort FR (Finnish Register Sample), most data is missing like the website. See screenshot (1), when no url is provided should we hide the white bar or say ‘no url available’. (2) the Description box is empty and much smaller then General design, might be better to scale Description the same as General Design? (3) Again empty but we can add some text as ‘No data available’
cohort-view

Adding a logo to the cohort works however I do not see the network Longitools in this case (screenshot below).
cohort-view-network

**Comment by connoratrug** [comment]
> For this example I used the cohort FR (Finnish Register Sample), most data is missing like the website. See screenshot (1), when no url is provided should we hide the white bar or say ‘no url available’. (2) the Description box is empty and much smaller then General design, might be better to scale Description the same as General Design? (3) Again empty but we can add some text as ‘No data available’ ![cohort-view]
> 
> Adding a logo to the cohort works however I do not see the network Longitools in this case (screenshot below). !

These are all (missing) data issues, suggest to add the data instead of messages targeted to data-managers instead of end-users

**Comment by EleanorHyde-UMCG** [comment]
Ziet er goed uit. Paar dingetjes:
- 'Website' text staat niet goed aligned met de rest, staat iets naar rechts 
- Suggestie: zie het voorbeeld in het Word doc. hier gaat het om netwerk 'ATHLETE' maar daar zou je alleen als kenner erachter komen omdat we alleen de naam voluit hier laten zien. Kunnen we hier (ook) het acronym gebruiken?
-
[20220110 testing cohort page.docx](https://github.com/molgenis/molgenis-emx2/files/7838929/20220110.testing.cohort.page.docx)

**Pull request merged**
