### PR TITLE
feat(pyclient): upload method for the Pyclient

### PR DESCRIPTION
**Pull request by YpeZ**
What are the main changes you did:
- added a method for uploading files to a database with the Pyclient

how to test:
- use the 'upload_file.py' script in the dev folder

todo:
- [x] updated docs in case of new feature
- [ ] added/updated tests
- [x] update status of upload progress
- [x] report the subtasks of the upload process
- [x] catch any errors that may be caused by this method

### CODE REVIEW

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
Tested:
- [x] Excel upload with data
- [x] zip file with data
- [x] zip file with molgenis.csv
- [ ] molgenis.csv
- [ ] data.csv

Upload of CSV still does not seem to work: I've both tested a molgenis.csv as well as data in a table. Upload returns message:
`INFO:Molgenis EMX2 Pyclient:add/update metadata success`

but the data is not saved.

**Comment by dtroelofsprins** [comment]
Tested CSV upload by using the UI:
- a datatable.csv works and returns "imported number of rows: 3"
- upload of molgenis.csv also works returns: "add/update metadata success"

With the Pyclient for both files "add/update metadata success" is returned, but in both cases nothing is actually uploaded.

**Comment by dtroelofsprins** [comment]
Just had a talk with Morris about this: 
Using the csv like this is not going to work for "tablename".csv's For this some backend changes are needed. As this takes some time, making upload of csv files possible would be to zip the file(s) and then use zip API. Which might be a good idea anyway as this makes data loads smaller.

**Comment by YpeZ** [comment]
@dtroelofsprins 
> Tested CSV upload by using the UI:
> 
>     * a datatable.csv works and returns "imported number of rows: 3"
> 
>     * upload of molgenis.csv also works returns: "add/update metadata success"
> 
> 
> With the Pyclient for both files "add/update metadata success" is returned, but in both cases nothing is actually uploaded.

I have fixed the issue where the `molgenis.csv` is not actually updated.
I also fixed the upload of data from for example `Data table.csv`. This requires however that a table named `Data table` exists on the schema, or else the `NoSuchTableException` is raised.
Lastly, I added the recommendation to zip the files first when multiple csv's are to be uploaded.

**Review by dtroelofsprins — APPROVED** [review]
Tested several uploads:
- [x] Excel upload with data
- [x] zip file with data
- [x] zip file with molgenis.csv
- [x] molgenis.csv
- [x] TableName.csv

Did a quick code review and no remarks related to this.

**Pull request merged**
