### PR TITLE
feat: add row clone button to table view

### PR DESCRIPTION
**Pull request by mswertz**
To test: in table explorer you see for each row a clone button.

### CODE REVIEW

**Comment by mswertz** [comment]
[#8489 copy row](https://trello.com/c/v9eky1EL/322-8489-copy-row)

**Comment by erikzwart** [comment]
Cloning or even inserting a new row does not work "column 'name' is required (and filled in) but null, see screenshot
molgenis-8 28 0_PR-741_insert-error
By clicking on the clone icon I would expect the popup to say 'Clone or Duplicate' not Update as it is right now.
The clone icon seems to disappear when the edit popup is show, see screenshot
molgenis-8 28 0_PR-741_clone-error_missing-icon

Last, the icon might not be clear for everyone, maybe add a popup text when you hover over it saying 'clone / copy row'?

**Comment by erikzwart** [comment]
Cloning or even inserting a new row does not work "column 'name' is required (and filled in) but null, see screenshot
molgenis-8 28 0_PR-741_insert-error
By clicking on the clone icon I would expect the popup to say 'Clone or Duplicate' not Update as it is right now.
The clone icon seems to disappear when the edit popup is show, see screenshot
molgenis-8 28 0_PR-741_clone-error_missing-icon

Last, the icon might not be clear for everyone, maybe add a popup text when you hover over it saying 'clone / copy row'?

**Review by erikzwart — CHANGES_REQUESTED** [review]
https://github.com/molgenis/molgenis-emx2/pull/741#issuecomment-976255303

**Review by erikzwart — CHANGES_REQUESTED** [review]
The clone icon seems to disappear when the edit popup is show, see screenshot.
molgenis-8 28 0_PR-741_clone-error_missing-icon

After clicking on the copy icon the popup menu title is 'Update ...' might be better to use 'Copy or Clone ..'?

Cloning or copying a row works perfect!

**Review by erikzwart — APPROVED** [review]

**Pull request merged**
