### PR TITLE
fix: Fix ssr render capability

### PR DESCRIPTION
**Pull request by connoratrug**
@molgenis/expressions can not be loadend into node context
remove untill replacement is created

related to https://github.com/molgenis/molgenis-expressions/issues/14

### CODE REVIEW

**Comment by mswertz** [comment]
Expressions don't need to run in ssr context. I choose to keep expressions.
In addition, business value of expressions is at the moment higher then ssr

**Review by mswertz — CHANGES_REQUESTED** [review]
expressions is a core feature heavily used in rare disease team. Please think of another way? What we could do, it is ugly, but is load the expression lib a separate dependency in header of  the index.html, as described on the expressions website. Then we don't need to import and thus don't impact other apps.

**Comment by connoratrug** [comment]
> expressions is a core feature heavily used in rare disease team. Please think of another way? What we could do, it is ugly, but is load the expression lib a separate dependency in header of the index.html, as described on the expressions website. Then we don't need to import and thus don't impact other apps.

Not suggesting to remove expressions, just disable it in the main components branch zo it can be fixen in a PR

**Comment by connoratrug** [comment]
> Expressions don't need to run in ssr context. I choose to keep expressions. In addition, business value of expressions is at the moment higher then ssr

No need to remove the Expressions feature, just remove the current lib from the components lib.

**Pull request merged**
