### PR TITLE
Feat: truncate button in table explorer

### LINKED ISSUE #139: Remove all data from a table/entity
**Describe the feature request**
I want to remove all the data from a table/entity so i can re-upload a new version of the data ( or just remove the data from the system).

**To Reproduce**
Sign in with right to 'delete' data in table x
navigate to a data table x
click a button to remove all rows of data in table x

and / or 

Have endpoint / mutation to remove all rows from a table x, if client passes correct token 

**Expected behavior**
System asks for confirmation  ( api can assume auto confirm )
All the data rows are removed from the table / system
If data in the table is being referenced by another table, the system should warn about this and not remove the data (, or clear out the links, or remove the referenced rows (cascade delete) .)

**Additional context**
UI / Docs should make it clear what happens to data used in other tables.

### PR DESCRIPTION
**Pull request by mswertz**
You can find the button under the 'bombshell'

image

closes #139

### CODE REVIEW

**Review by marijevdgeest — COMMENTED** [review]
I can't always truncate all data, even though a truncated the reference table before:

**Comment by mswertz** [comment]
> Hint: Truncate table "Order" at the same time, or use TRUNCATE ... CASCADE.

Hi, I think this works as intended because it prohibits the truncate if there are foreign key relations (in this case, error says Orders have references to Pets, and thus you can't truncate Pets.

A more daring options is to enable 'CASCADE' as the message suggest. However, then automatically, if you delete Pets then all associated Orders will be deleted.

We could make this an optional feature, i.e., you can check a box saying you would like to cascade or not.
What do you think @marijevdgeest ?

**Comment by marijevdgeest** [comment]
Yes the other table, 'Order', was already empty! For me a cascade option is not really necessary, I think it's saver to do without

**Comment by mswertz** [comment]
indeed an error. Should have read manual on truncate. Rewrote to use delete instead.

**Review by marijevdgeest — APPROVED** [review]

**Comment by erikzwart** [comment]
[#9245 As datamanager I want 'delete data' (truncate) option for tables in the catalogue](https://trello.com/c/RLEnKGuw/506-9245-as-datamanager-i-want-delete-data-truncate-option-for-tables-in-the-catalogue)

**Pull request merged**
