### PR TITLE
fix: logos should not be stretched

### PR DESCRIPTION
**Pull request by mswertz**
Before
image

After:
image

Thank you to @jelmerveen

### CODE REVIEW

**Review by connoratrug — CHANGES_REQUESTED** [review]
use/moe to  card component from lib, it avoids have to fix the same issues again and again

**Comment by connoratrug** [comment]
how can this be testen on: https://preview-emx2-pr-1416.dev.molgenis.org/test%20network%20img%20card/catalogue/#/

**Comment by mswertz** [comment]
You could use https://preview-emx2-pr-1416.dev.molgenis.org/test%20network%20img%20card/catalogue/#/networks-catalogue but you need to upload a logo into a network (todo: update example data).

**Review by connoratrug — APPROVED** [review]
Seems oke for a quick 'fix' but needs to be moved to testable component lib , see https://emx2.dev.molgenis.org/apps/styleguide/#imagecard code for example of combining emx with bootstap img classes

**Pull request merged**
