### PR TITLE
add doc on datamodel update procedure

### PR DESCRIPTION
**Pull request by BrendaHijmans**

### CODE REVIEW

**Comment by erikzwart** [comment]
[#8588 Document the current procedure of data-catalogue and staging](https://trello.com/c/MgHgiRnD/363-8588-document-the-current-procedure-of-data-catalogue-and-staging)

**Review by erikzwart — CHANGES_REQUESTED** [review]
Fixed some broken links and added some, please have a look at the commits

**Comment by BrendaHijmans** [comment]
> Fixed some broken links and added some, please have a look at the commits

link to molgenis.csv does not work for me, should be: https://github.com/molgenis/molgenis-emx2/blob/master/data/datacatalogue/molgenis.csv

**Comment by BrendaHijmans** [comment]
> More of a general question of this datamodel update procedure, why are we doing most (if not all) of these steps by hand and not programmaticly. For small changes I can understand but a lot of these changes have a lot of moving parts and touch multiple code libs as describes in the steps 1 through 7. I’m not the expert here but we are using continous intergration if I understand correctly, then it should be possible to do the same thing for database changes as well?

We have indeed been discussing to automate data migration. We should make a story for this in trac and see how to go about automating the different processes involved in changing the datamodel. Staging area models can be automatically generated from the main model. Most data migrations can be automated, though some migrations require knowledge about the data structure that may be hard to automate.

**Review by erikzwart — APPROVED** [review]

**Review by mswertz — APPROVED** [review]

**Pull request merged**
