### PR TITLE
feat: only use email service if message selector is configured

### LINKED ISSUE #3551: Sending an email from the 'contact' page on a cohort gives an error message
**What version of EMX2 are you using (see footer)**
Software version: [v10.48.8](https://github.com/molgenis/molgenis-emx2/releases/tag/vv10.48.8). Database version: 18.

**Describe the bug**
Sending an email from the 'contact' page on a cohort gives an error message.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/cohorts/testCohort2
2. Click on Contact
3. Fill in test name, your own email address and test message
4. Press Send
5. See the error pop-up: "
image

**Expected behavior**
I would expect an email to be sent to my email address and the pop-up to be closed automatically so that I return to the cohort detail page

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome 
 - Version Versie 122.0.6261.95 (Officiële build) (64-bits)

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #3551

how to test:
- Check that 'contactRecipientsQuery' has been set for this server and schema; click the contact btn, a message should be send.
- optional , save the value from 'contactRecipientsQuery' to put back later
- remove the 'contactRecipientsQuery'  setting for this server and schema; click the contact btn, a adress to send an email to should be shown.
- Add / putback the 'contactRecipientsQuery' values ( make sure it is a valid value)  for this server and schema; click the contact btn, a message should be send.
-
todo:
- [ ] updated docs in case of new feature
- [ ] added tests
- [ ] updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Comment by EleanorHyde-UMCG** [comment]
What was supposed to happen here? I got:
- CONTACT button still there --> press it
- get this pop-up, with fields to fill in taken away, but still 'Send' button and this doesn't actually do anything

image

**Comment by connoratrug** [comment]
i nice catch we should remove the btn

**Comment by EleanorHyde-UMCG** [comment]
Clicking on the email address in the pop-up, however, DOES open an initial email to Molgenis Support in Outlook. The idea, I thought, was to click on Contact and then immediately open the initial email to the email address on the cohort. Not sure which middle way this currently is?

**Review by erikzwart — APPROVED** [review]
Unable to test the email form, preview not configured.

Pressing the contact button shows the correct detail modal:
image
Send button is NOT shown.

**Comment by connoratrug** [comment]
> Clicking on the email address in the pop-up, however, DOES open an initial email to Molgenis Support in Outlook. The idea, I thought, was to click on Contact and then immediately open the initial email to the email address on the cohort. Not sure which middle way this currently is?

it use to be like this , but we can add it on top

**Pull request merged**
