### PR TITLE
feat: add pr previews

### PR DESCRIPTION
**Pull request by sidohaakma**
Changes:

- Chart is now build and published on the chart repo during merge
- Chart is using the MOLGENIS version (we could do this differently and only trigger the chart build when chart files are changed)
- The PR flow differs now from the master build in terms of rancher deployment and chart builds
- The pod-template is in a separate file in `.jenkins/build-pod.yaml` to clean up the Jenkinsfile
- The build result is posted on slack in the **pr-emx2** channel

### CODE REVIEW

**Comment by sidohaakma** [comment]
[#8132 Updated EMX2 Jenkins pipeline so we can easily get previews for each open pull request](https://trello.com/c/Oj0GxVwP/194-8132-updated-emx2-jenkins-pipeline-so-we-can-easily-get-previews-for-each-open-pull-request)

**Review by mswertz — APPROVED** [review]

**Comment by mswertz** [comment]
We decided to merge this on monday to not break the build

**Review by mswertz — CHANGES_REQUESTED** [review]
I get error at sign in 
image

**Comment by sidohaakma** [comment]
> I get error at sign in
> image

Return type of the `Record.get` method returns `null`. GraphQL can not cast `null` to a `boolean` class. This seems to me like something went wrong in the lower parts of emx2.

**Review by mswertz — APPROVED** [review]

**Pull request merged**
