### PR TITLE
fix: label 'documentation' should be same as in data model (was: "attached fileds")

### PR DESCRIPTION
**Pull request by mswertz**
changes:
- renamed attached files to 'documentation' (that is the name in the data model)
- remove unnecessary subheaders for 'images' and 'documents'

### CODE REVIEW

**Review by connoratrug — DISMISSED** [review]
suggest to update datamodal, the files are 'attached files' and not documentation

**Comment by mswertz** [comment]
> suggest to update datamodal, the files are 'attached files' and not documentation

No they are not. They are either links or attached files.
The intent of this field is to provide documentation. Attached files is meaningless.

**Comment by EleanorHyde-UMCG** [comment]
Currently what I'm seeing is:
- in the chapters on the LHS: "Documentation"
- in the block on the RHS: heading "Attached files" and text below that "Documents"

Not sure if this was intended?

**Comment by mswertz** [comment]
> Currently what I'm seeing is:
> 
> * in the chapters on the LHS: "Documentation"
> * in the block on the RHS: heading "Attached files" and text below that "Documents"
> 
> Not sure if this was intended?

Thx. RHS should then be updated as well.

**Comment by mswertz** [comment]
> Currently what I'm seeing is:
> 
> * in the chapters on the LHS: "Documentation"
> * in the block on the RHS: heading "Attached files" and text below that "Documents"
> 
> Not sure if this was intended?

you are correct. fixed now

**Pull request merged**
