### PR TITLE
fix(catalogue):  4367 format date as year

### LINKED ISSUE #4367: fix(catalogue): correction of the yy-mm-dd date format into yyyy-yyyy for start/end years needs to be carried out on the collection event, too
testplan 5, step 48
1. go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/cohorts/testCohort2
2. scroll down to collection events
3. click on test collection event for cohort 2
4. see that the start/end year is still in yy-mm-dd format.

This needs to be in yyyy-yyyy format.

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #4367

What are the main changes you did:
- format the date as year

note: might be more of a model issue , would be nice to get the format from the metadata 
used to be everything was a date, catalogue model now has mix; date, year as number , year as string , maybe others 
todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Comment by mswertz** [comment]
> t be more of a model issue , would be nice to get the format from the metadata
> usedto be everything was a date, catalogue model now has mix of data, year as number , year as string , maybe others
> todo:

indeed. We already have period data type, a year data type would make sense.

**Comment by mswertz** [comment]
> > t be more of a model issue , would be nice to get the format from the metadata
> > usedto be everything was a date, catalogue model now has mix of data, year as number , year as string , maybe others
> > todo:
> 
> indeed. We already have period data type, a year data type would make sense.

And more generally, why don't we show the date if it is a date?

**Comment by mswertz** [comment]
@BrendaHijmans if we use date then we should show the date? or should we revert to year?

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
The issue linked to this PR was closed after this comment:
"Why are we changing a date that is filled out into year? We made a deliberate choice to include start and end date into the collection events and end year/start year for resources. Data collection period may be more precisely recorded than the start/end of a resource."

**Pull request closed without merging**
