### PR TITLE
feat: added LANDING_PAGE setting 

### PR DESCRIPTION
**Pull request by mswertz**
to make users directly go to path you like the to go, skipping /apps/central

To test:
* sign in as admin
* use admin settings -> LANDING_PAGE and set that to /pet store/
* open new browser and go to root of the preview server, you will see you navigate to /pet store/ instead of /apps/central/

You can still go back to /apps/central using the breadcrumb pull down.

TODO: if you have no permission on the url the breadcrumb doesnt show well

NOTE: refactored settings internals at backend to fix a bug where settings could have duplicate key

### CODE REVIEW

**Review by connoratrug — COMMENTED** [review]
isOidcEnabled is no longer shown in settings , is this a feature or bug and why is this change part of the landing page setting PR ?

**Review by connoratrug — COMMENTED** [review]
Create a new setting with the same name overrides the previous setting ( i would expect a warning or error)

**Review by connoratrug — CHANGES_REQUESTED** [review]
works nice.
Overriding the setting by using the same name seems like a bug to me

**Comment by mswertz** [comment]
> Overriding the setting by using the same name seems like a bug to me

I think that if you create a new setting with same name it should override the previous setting.
At least, that is how I would expect it to work. In any case, this is another issue not changed by this PR.
The bug in previous version was that if you add a setting with same key then you had two settings with that key.
That is not how settings is intended to work, and in graphql the last setting will then 'win'.

**Comment by connoratrug** [comment]
> > Overriding the setting by using the same name seems like a bug to me
> 
> I think that if you create a new setting with same name it should override the previous setting. At least, that is how I would expect it to work. In any case, this is another issue not changed by this PR. The bug in previous version was that if you add a setting with same key then you had two settings with that key. That is not how settings is intended to work, and in graphql the last setting will then 'win'.

oke

**Review by connoratrug — APPROVED** [review]

**Pull request merged**
