### PR TITLE
feat: allow up/download table CSV by name or id

### PR DESCRIPTION
**Pull request by mswertz**
demo:
- I can upload csv and excel files containing a table, where table name can be case and space agnostic. 

Following request of @YpeZ, uploading a CSV file for one table when having spaces in the name it fails:

image

In current version for some reason we assume CSV and Excel up/downloads to use the 'id' of the table.
That is silly because we typically upload the csv files from a data.zip and then those use 'name' of the table
So this feature makes it possible to use both 'name' and 'id' (with us prefering to use the 'name').

how to test:
- upload table like 'Collection events.csv' and 'CollectionEvents.csv' should both work
- discussion: make it case insensitive too?

### CODE REVIEW

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
Functional test:
1.) The preview has an issue with the theme.css. I've also rebuild the PR, but issue is still there. I'm not sure if this is caused by the changes in the PR or due to something else.
2.) I've tested several options:
image

In all cases uploading excel/zip or csv with tableName works OK now. However, I'm not able to upload any type of file with the tableID as name, which should be the case as the title of the PR indicates, or am I wrong?

tablename and tableid are table1 and Table1 respectively

**Comment by mswertz** [comment]
this PR didn't yet consider Excel, only csv. But the errors you report there are indeed correct. Will update title to make clear it is about the csv,

**Comment by harmbrugge** [comment]
Fixed @dtroelofsprins comments, except for the xls table names (sheet tab name), could implement this if needed.

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
Tested several CSV file name options, all works fine, except a zipped file with tableID.csv:
image

**Review by harmbrugge — APPROVED** [review]

**Review by dtroelofsprins — APPROVED** [review]
All use cases work fine now :-)

**Pull request merged**
