### PR TITLE
fix: upload in inherited tables should throw duplicate key if same key is used in different tables

### LINKED ISSUE #594: Unable to upload inheritance trees when subtrees have same identifier
**What version of EMX2 are you using (see footer)**
8.15.1

**Describe the bug**
Unable to add OntologyTerms item

Multiple tables like DatabankFamilies, InstitutionRoles, PopulationEntryCauses, etc. store there values in OntologyTerms. The issue now is that I want to be able to add ‘other’ to DatabankFamilies and InstitutionRoles. This will not work because I can not add this value ‘other’ twice, see error message.

The situation now is that I can define ‘other’ one time for the table DatabankFamilies for instance and not use ‘other’ for any different table like InstitutionRoles.. 

**To Reproduce**
1. Go to 'https://minerva.molgeniscloud.org/'
2. Go to 'DatabankFamilies'
3. And add new item 'other'

**Expected behavior**
Be able to either select 'other' from a list of already defined OntologyTerms or be able to add 'other' and make sure the error does not occur.

**Screenshots**
molgenis-dup-OntologyTerms

molgenis-ontology-terms

**Desktop (please complete the following information):**
 - OS: ubuntu 20.04
 - Browser chromium
 - Version 93.0.4577.82

**Additional context**

### LINKED ISSUE #824: Download then upload of complete schema fails
**What version of EMX2 are you using (see footer)**
8.33.0

**Describe the bug**
Import failed: Transaction failed: insert or update on table "CollectionEvents" violates foreign key (ref_array) constraint.Key ("sampleCategories")=(Other) is not present in table "SampleCategories", column(s)("name"): Cannot commit transaction in 9298ms

**To Reproduce**
1. Go to 'https://emx2.test.molgenis.org'](https://catalogue-acc.molgeniscloud.org/UMCG/updownload/
2. Download as zip
3. Upload into empty database

**Expected behavior**
Upload success, data and schema are copied into new schema

### LINKED ISSUE #1002: Unable to round trip data
**What version of EMX2 are you using (see footer)**
8.52.0

**Describe the bug**
Data import into empty schema fails 

**To Reproduce**
Go to server en download all data al zip  ( for example; https://emx2.molgeniscloud.org/Catalogue/updownload/)
Go to other server and upload all data into empt schema ( for example; localhost)

**Expected behavior**
Data gets uploaded, schema is created and filled with data

### PR DESCRIPTION
**Pull request by mswertz**
This fixes that issue that if you have subclasses, and then identifiers of rows in the subclass tables are the same that it will throw an error (instead of silently overwriting). See example of Brenda below, about SourceVariables and RepeatedSourceVariables that have the same name and then one hides the other.

fixes #824. 
fixes #594. 
possibly also fixes #1002 
Also the use case in catalogue staging, where RepeatedSourceVariables had overwritten SourceVariables
Note: we don't use this ontology structure but bug also emerges in catalogue model with inherited tables.

This PR contains:
- trigger to check and prevent updates on another mg_tableclass than inserted
- fix of test data set that did not conform to this

To test:
- create a main table 'pets' with primary key 'name'
- create an extended table 'cats' extends 'pets'
- using csv/excel: upload a 'pooky' into pets and also into 'cats'

behavior before the fix: 
- you will only see a record in 'cats', the 'pets' is empty

behavior after fix: 
- you will receive duplicate key exception on 'cats' that pooky already exists in 'pets'

### CODE REVIEW

**Comment by mswertz** [comment]
> Upload of repeats with the same name as a SourceVariable is now blocked. 

That is a good thing right?

> Error message is elusive:
> 
> Import failed: Transaction failed: record "old" has no field "dataDictionary".: Cannot commit transaction in 125ms

Indeed, well spotted. This had to do with composite keys. Should now be fixed.

**Comment by mswertz** [comment]
[BUGFIX: fix: upload in inherited tables should throw duplicate key if same key is used in different tables](https://trello.com/c/SN3Nl1rW/531-bugfix-fix-upload-in-inherited-tables-should-throw-duplicate-key-if-same-key-is-used-in-different-tables)

**Comment by mswertz** [comment]
[BUGFIX: upload in inherited tables should throw duplicate key if same key is used in different tables](https://trello.com/c/rNeXCupR/532-bugfix-upload-in-inherited-tables-should-throw-duplicate-key-if-same-key-is-used-in-different-tables)

**Review by erikzwart — APPROVED** [review]
Created a table Cats that extends Pet, tried to upload Pooky in Pet and Cats and got this error which you should expect. Works as intended:
image

**Pull request merged**
