### PR TITLE
fix(catalogue): Year 0 harmonisation matrix check mark is displayed while there is no data for this mapping.

### LINKED ISSUE #4428: Year 0 harmonisation details check mark is displayed while there is no data for this mapping
**What version of EMX2 are you using (see footer)**
v11.25.2

**Describe the bug**
Year 0 harmonisation details are not displayed in variable harmonisations detail view.

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/testNetwork1/
2. Click on Variables
3. Click on testVarRepeats_
4. See in harmonisation matrix ('Harmonisation status per data source') that Year 0 to Year 10 are present (so 11 variables) and that testCohort 1 has harmonised Year 0 to Year 10
5. Go to the underlying data: https://data-catalogue-acc.molgeniscloud.org/testCatalogue/tables/#/VariableMappings
6. Search for testVarRepeats. 
7. See that there is no mapping to year 0 for testCohort1 for testVarRepeats

### PR DESCRIPTION
**Pull request by mswertz**
closes #4428

### CODE REVIEW

**Review by hslh — DISMISSED** [review]
Functionality on preview is correct, fixes the original issue. 

However... now I've noticed that the text under DEFINITION still says 'Repeated for Year 0-10'. Is that something to fix in this PR as well, or should I make a separate issue?
Screenshot 2024-12-10 at 11 32 48

**Comment by mswertz** [comment]
> Functionality on preview is correct, fixes the original issue.
> 
> However... now I've noticed that the text under DEFINITION still says 'Repeated for Year 0-10'. Is that something to fix in this PR as well?

will take a look. might be same issue with some wrong defaults.

**Comment by hslh** [comment]
I see, my comment was wrong. The variable has repeats 0-10, but all the variables from the testCohorts only have mappings 1-10. So the text under DEFINITION was correct.

**Review by hslh — APPROVED** [review]
Looks good to me

**Pull request merged**
