### PR TITLE
feat: show matching items when searching

### LINKED ISSUE #3557: Show the actual matching items in the diagnosis tree when searching
**Is your feature request related to a problem? Please describe.**
When I search the diagnosis filter it only shows the root item under which a matching item falls, but as a user I might not realise that what I'm searching for is a child item of that item.

**Describe the solution you'd like**
When searching open the entire path to the matching items and highlight the matching items

### PR DESCRIPTION
**Pull request by chinook25**
What are the main changes you did:
- implements the expand part of #3557 

how to test:
- see issue, when searching inside the diagnosis available filter it should expand all the results.

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
Works and just filtering is sufficient no highlighting necessary, but I noticed two issues:
- when I search for 'colon' the view scrolls to the right and you cannot see the hierarchy anymore
- I can't switch to Orphanet anymore

**Review by dtroelofsprins — COMMENTED** [review]
The issues raised by Esther are solved.
When searching for a specific term all search results are nicely shown however:
When searching for colon in Orphanet and you select the first 'root' the other roots get a blue - (minus) sign and even some of the children are selected, without selecting them.
image

This does not happen with ICD.

**Comment by dtroelofsprins** [comment]
Oh bit stupid of me, I suddenly get it, that's of course because a child can have multiple parents and I selected one of his other ones ones.

**Comment by konstantina-gkp** [comment]
When searching for the word "iron"in the diagnosis filter, the filter returns all the fields matching the search term. However, the filter also retrieves unrelated diagnoses, such as "environmental", as illustrated in the image below.

search_diagnosis_filter

Shouldn't the search functionality be more specific to avoid such results?

**Comment by chinook25** [comment]
> When searching for the word "iron"in the diagnosis filter, the filter returns all the fields matching the search term. However, the filter also retrieves unrelated diagnoses, such as "environmental", as illustrated in the image below.
> 
> search_diagnosis_filter
> 
> Shouldn't the search functionality be more specific to avoid such results?

Maybe, but that's out of the scope of this PR. If we want that, a new feature request should be made :)

**Comment by dtroelofsprins** [comment]
I agree, and there is already an issue which relates to this: #3558

**Review by dtroelofsprins — APPROVED** [review]

**Pull request merged**
