### PR TITLE
fix: jit should be off to prevend slow queries. closes #3652. closes #3476

### LINKED ISSUE #3476: Query in networks table runs out of time for data model v 3.12 on dev server, not on data catalogue server
**What version of EMX2 are you using (see footer)**
10.45.1

**Describe the bug**
When loading demo data in the DATA_CATALOGUE data model via the template reader, there is an error when viewing the Networks table. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/
2. Click on + to create a new schema
3. Under template select 'DATA_CATALOGUE', load example data = True
4. wait a while for data to load, finish of loading will not be prompted (see issue: https://github.com/molgenis/molgenis-emx2/issues/3059)
5. refresh page and open newly made schema
6. move to table Networks
7. See error

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### LINKED ISSUE #3652: Cannot view Cohorts table due to time out error
**What version of EMX2 are you using (see footer)**
10.58.0, 10.58.1, also older 10.48.8

**Describe the bug**
I cannot view the Cohorts table due to an error.
image

**To Reproduce**
1. Go to https://data-catalogue.molgeniscloud.org/catalogue/tables/#/Cohorts

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by mswertz**
closes #3652 
 closes #3476

What are the main changes you did:
- added SET jit = off info where needed

how to test:
- compare #3652 
- compare #3476

todo:
- [x] updated docs in case of new feature
- [x] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Comment by mswertz** [comment]
doesn't yet perform as expected.

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
Code seems fine, but I'm not seeing the expected performance improvements. I'm wondering if we can actually set it like this.
If I set it in the configuration and restart postgresql then the Directory can query the ICD-10 block C00-C75, without setting it in configuration it will time out even with this fix.
The documentation doesn't hint at per user or schema configuration, so probably the best thing to do is just check if it is disabled and notify it as an warning if it is not disabled.

**Comment by mswertz** [comment]
BEFORE: 
image

AFTER:
https://preview-emx2-pr-3704.dev.molgenis.org/catalogue-demo/tables/#/Cohorts

This is quite a small difference and we might not have applied the jit=off.
image

**Comment by mswertz** [comment]
> I cannot review the code, so this is just a comment on the functionality. I can view Networks and Cohorts in the table view again without issues. The variable explorer in the ssr UI may be slower, can someone check this with actual timings in code?

For this another PR is needed. Because indeed some queries might be slower but generally it is faster.

**Review by dtroelofsprins — APPROVED** [review]
I've checked some queries using the biobank directory App and jit = off is implemented the preview, as these queries are definitely faster there (give results where if jit is not off, these get stuck).

**Review by esthervanenckevort — APPROVED** [review]
Tested it locally and it works.

**Pull request merged**
