### PR TITLE
feat(directory): publish studies

### PR DESCRIPTION
**Pull request by dtroelofsprins**
### What are the main changes you did
- included the studies table in the publish steps
- included a .env_example file

### How to test
- Create two schemas, one based on BIOBANK_DIRECTORY template and one on BIOBANK_DIRECTORY_STAGING template and include demo data on a server and test it using dev.py

### CODE REVIEW

**Review by esthervanenckevort — APPROVED** [review]
Code changes look fine to me, but I'm not able to test it, so should await a review from Hessel before merging.

**Review by hslh — CHANGES_REQUESTED** [review]
Publishing local nodes fails with the following error:

💾 Saving new and updated data to Directory tables
INFO:Molgenis EMX2 Pyclient:200
INFO:Molgenis EMX2 Pyclient:Import from store for 39ms
INFO:Molgenis EMX2 Pyclient:    Imported 7 Persons in 13ms (538 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 AlsoKnownIn in 16ms (187 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 Networks in 17ms (176 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 2 Biobanks in 12ms (166 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 1 Studies in 8ms (125 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 Collections in 33ms (90 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 108 CollectionFacts in 96ms (1125 items/sec)
INFO:Molgenis EMX2 Pyclient:Committing for 8ms
INFO:Molgenis EMX2 Pyclient:Completed task: Import csv file in 230ms
🧼 Cleaning up removed data in Directory tables
        Deleting 1 row(s) in Studies
INFO:Molgenis EMX2 Pyclient:Deleted data from test-4511::Studies.
            ⚠️ ID bbmri-eric:studyID:DE_112233 is deleted
        Deleting 1 row(s) in AlsoKnownIn
INFO:Molgenis EMX2 Pyclient:Deleted data from test-4511::AlsoKnownIn.
            ⚠️ ID bbmri-eric:akiID:DE_00002 is deleted
        Deleting 2 row(s) in Persons
ERROR:Molgenis EMX2 Pyclient:Delete into table Persons failed: Transaction failed: update or delete on table "Persons" violates foreign key constraint "Services.contactInformation REFERENCES Persons" on table "Services". Details: Key (id)=(bbmri-eric:contactID:contact_bb1) is still referenced from table "Services".

Staging an external node fails with this error:

:earth_africa: Node NL (Netherlands)
:inbox_tray: Staging data of node NL
    :package: Retrieving node's data from https://bbmri-emx2-test.molgeniscloud.org/
    :fire: Clearing staging area of NL
ERROR:Molgenis EMX2 Pyclient:Delete into table Studies failed: Transaction failed: delete on table "Studies" violates foreign key constraint. Details: Key ("id")=(bbmri-eric:studyID:NL_112233) is still referenced from table "Collections", column(s)("studies")

**Review by hslh — CHANGES_REQUESTED** [review]
Staging from an external node now works, but this error persists:

🎁 Publishing nodes
💾 Saving new and updated data to Directory tables
INFO:Molgenis EMX2 Pyclient:200
INFO:Molgenis EMX2 Pyclient:Import from store for 11ms
INFO:Molgenis EMX2 Pyclient:    Imported 7 Persons in 11ms (636 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 AlsoKnownIn in 6ms (500 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 Networks in 5ms (600 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 2 Biobanks in 6ms (333 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 1 Studies in 5ms (200 items/sec)
INFO:Molgenis EMX2 Pyclient:    Imported 3 Collections in 15ms (200 items/sec)
INFO:Molgenis EMX2 Pyclient:Completed task: Import csv file in 175ms
🧼 Cleaning up removed data in Directory tables
        Deleting 3 row(s) in Persons
ERROR:Molgenis EMX2 Pyclient:Delete into table Persons failed: Transaction failed: update or delete on table "Persons" violates foreign key constraint "Services.contactInformation REFERENCES Persons" on table "Services". Details: Key (id)=(bbmri-eric:contactID:contact_bb1) is still referenced from table "Services".

**Comment by dtroelofsprins** [comment]
> But that is only a problem when using it with demo data, I assume?

True

**Pull request merged**
