### PR TITLE
feat(central): remove and enable/disable users via admin ui

### PR DESCRIPTION
**Pull request by MaxPostema**
fixes: #3981

What are the main changes you did:
- remove user button
- enable and disable user accounts toggle

how to test:
- Go to: apps/central/#/admin/users
- create a user / remove users 
- try to disable an user and login

todo:
- [ ] updated docs in case of new feature
- [x] added/updated tests
- [x]  combine removeUser and deleteUser?
- [x] backend and frontend should not be able to disable "anonymous and admin"

### CODE REVIEW

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
Did a functional test:
- I like the option to disable a user, when checking the user list it however seems a bit as if all users are disabled and the disabled ones are valid (looking at the sign of the person 
image, but when hoovering over it is already clearly indicated => and also the values in the enabled column are clear enough.
- Deleting a user works fine, however, when it's in a member list in a schema it does not get removed there => which makes me wonder if it's really removed from the backend as I would think that the "userlist" in admin would be the main source?

**Review by mswertz — CHANGES_REQUESTED** [review]
nice.
should not be able to disable anonymous
should have more test coverage?

**Review by dtroelofsprins — APPROVED** [review]
Functional review:

- [x] disable user, user cannot login, with warning that account has been disabled. Keeps schema permissions.
- [x] admin and anonymous can't be disabled/deleted (great addition, you think it's obvious, but been there, done that for anonymous..., only backup restore could solve it :sweat_smile: )
- [x] delete user, with are you sure? notification => user is deleted including all schema permissions.

**Review by harmbrugge — APPROVED** [review]
Code looks good

**Pull request merged**
