### PR TITLE
fix: search should work as (term1 and term2)

### LINKED ISSUE #3850: Filtering in Variable Explorer needs tweaking (combination of search filters, topic filters and cohort filters, and how search filters behave)
**What version of EMX2 are you using (see footer)**
Software version: v10.77.4

**Describe the bug**
When filtering on variables using search filters, cohort filters and topic filters, the combination is not applied correctly, meaning that too many variables are shown.

Agreed-upon query is:
(search bar criteria) AND (topic criteria) AND (cohort criteria)

The query _within_ each place to filter is as follows:
search bar: additive, searchterm1 AND searchterm2
topics: topic1 OR topic2 (or both)
cohorts: cohort1 OR cohort 2 (or both)

**To Reproduce**
1. Go to https://data-catalogue-acc.molgeniscloud.org/testCatalogue/ssr-catalogue/all/variables
2. Choose subtopic ‘family and household structure’ and subtopic ‘language’ (under 'socio-demographic...'--> you get 12 vars
3. Add ‘birth’ in search bar --> list reduces to 3 vars
4. Select cohorts ‘NFBC1966’, ‘PELAGIE’ and ‘SEPAGES’ --> all 3 vars are still shown
5. Go to the Harmonisation Matrix (button 'Harmonisations'), see that all 3 vars are still shown
6. Remove the selection of cohort PELAGIE
7. See error: all 3 variables are still shown even though NFBC1966 and SEPAGES only have mappings to cohab_0.

**Expected behavior**
Only cohab_0 should be shown.
WILL FIND OTHER TEST DATA EXAMPLES LATER!

**Screenshots**

Image

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome

### PR DESCRIPTION
**Pull request by mswertz**
closes #3850 

What are the main changes you did:
- when using search as filter (not as part of seperate search parameter) it returned (term1 OR term2). Desire is to have it term1 AND term2
- TEXT_SEARCH operator should be used in graphql api until TRIGRAM_SEARCH is better understood

how to test:
- test search in variables user interface which uses this feature
- see unit test

todo:
- [x] added/updated tests
- [x] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Comment by EleanorHyde-UMCG** [comment]
I can't get it to work in prev (no. 3865).

testdata in DEV:
'adhd' in search bar --> 14 variables
'maternal' in search bar --> 710 variables
'maternal adhd' and 'adhd maternal' in the search bar should give the same results i.e. somewhere between 710 and (710+14) variables (depending on how many match both criteria, impossible to know with this test data)

**Comment by mswertz** [comment]
> I can't get it to work in prev (no. 3865).
> 
> testdata in DEV: 'adhd' in search bar --> 14 variables 'maternal' in search bar --> 710 variables 'maternal adhd' and 'adhd maternal' in the search bar should give the same results i.e. somewhere between 710 and (710+14) variables (depending on how many match both criteria, impossible to know with this test data)

https://preview-emx2-pr-3865.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/variables?page=1&conditions=[{%22id%22:%22search%22,%22search%22:%22adhd+mother%22}]

gives the desired results?

**Comment by EleanorHyde-UMCG** [comment]
> > I can't get it to work in prev (no. 3865).
> > testdata in DEV: 'adhd' in search bar --> 14 variables 'maternal' in search bar --> 710 variables 'maternal adhd' and 'adhd maternal' in the search bar should give the same results i.e. somewhere between 710 and (710+14) variables (depending on how many match both criteria, impossible to know with this test data)
> 
> [https://preview-emx2-pr-3865.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/variables?page=1&conditions=[{%22id%22:%22search%22,%22search%22:%22adhd+mother%22}]](https://preview-emx2-pr-3865.dev.molgenis.org/catalogue-demo/ssr-catalogue/all/variables?page=1&conditions=%5B%7B%22id%22:%22search%22,%22search%22:%22adhd+mother%22%7D%5D)
> 
> gives the desired results?

The filter works well and gives the same answer whether you put "termA termB" or "termB termA", only I just need to check why testvarNoRepeats is now shown (not aware that the word 'mother' is used on that one, but I'll check).

**Comment by mswertz** [comment]
> testvarNorepeats does not have the word 'mother' anywhere in it as far as I can see. If the search bar ALSO searches in the keywords, then you could use the following test data and test the different combinations of words entered:
> 
> image

The search looks in columns of Variables table (and its superclass) as well as in the columns of the ontology terms that are referred (e.g. if the word is in description of an areas of information than it will be found)

**Comment by mswertz** [comment]
Actually, keyword=Language also matches 'mother', see https://preview-emx2-pr-3865.dev.molgenis.org/CatalogueOntologies/tables/#/Keywords and then search for 'mother' because of 'mother tongue'

**Comment by EleanorHyde-UMCG** [comment]
Tested in prev 3865.  
Search bar: "var" --> 132 variables, including non-test variables and all the test variables
Search bar: "var test" --> 20 variables, including non-test variables and all the test variables
Search bar: "var test vir" --> only 2 variables, both test variables with 'vir' in the name (and Virology as keyword)

**Review by EleanorHyde-UMCG — APPROVED** [review]

**Pull request merged**
