### PR TITLE
feat: network in networks

### PR DESCRIPTION
**Pull request by connoratrug**
if vieuwing a spesific catalogue then change the network query to filter on networks belonging to that catalogue

- update query for list view
- update query for overview page

@mswertz not sure if the direction we want to go, the data query sort of works but the the same thing can not be done fore the agg_count this then breaks the paging. maybe change datamodel and maybe just have separate pages of all en [catalogue] routes

### CODE REVIEW

**Comment by mswertz** [comment]
I noticed you not using filters on graphql subqueries, after review understood that was because they were partly missing. Lets call that a bug and therefore I added the missing filter options so we can do the limit/offset and filtering server side. We should discuss with @BrendaHijmans what filters make sense, for now only 'search' and 'type'.

**Review by mswertz — APPROVED** [review]
I pushed some fixes. 

Probably this can be merged and the after review we can refine. 

I think in particular the networks/[id].vue needs to be improved but need input from the data managers for that.

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
Outlining of the landing page needs work:
image

Also, here, when there are more than 3 categories of resources to display:

image

**Comment by BrendaHijmans** [comment]
Missing functionality:
-Should you be able to move from Network of networks (e.g. EUChildNetwork) to underlying network (e.g. ATHLETE only)? Now you can move to the descriptives of an underlying network, but not to the landing page of an underlying network.
-Link to data resources from one 'category' on the landing page: instead of Cohorts, Data sources (databanks?) separately have one Data resources.

**Comment by mswertz** [comment]
For the outlining, see PR https://github.com/molgenis/molgenis-emx2/pull/3068

**Comment by mswertz** [comment]
> -Link to data resources from one 'category' on the landing page: instead of Cohorts, Data sources (databanks?) separately have one Data resources.

What do you mean? In the feature I would like to merge Cohorts, Databanks, Data sources etc into 1 list, is that what you mean?

**Pull request merged**
