### PR TITLE
feat: because you searched for more filters

### LINKED ISSUE #3597: Directory App: Some filters do not show "because you searched for"
**What version of EMX2 are you using (see footer)**
v10.49.9

**Describe the bug**
Diagnosis available and biobank services filter, do not show "because you searched for filter value", while all other filters do.

**To Reproduce**
1. Go to 'https://directory-emx2-acc.molgenis.net'
2. Click on Diagnosis available filter and select U07.1. 
3. Wait to see the filter results
4. No "because you searched for" message is displayed
5. Add categories filter: covid-19 and see the message in the selected collections
6. Add material type feces and this is added to the message
7. Remove all filters and select biobank services = Antibody Development => no message is shown.

**Expected behavior**
When using the Diagnosis Available and Biobank Services filter, the reason why collections are shown should be displayed via message "because you searched for"

**Screenshots**
EMX2:
image

EMX1 (https://directory.bbmri-eric.eu):
image

**Additional information**
For some reason in the EMX1 Directory App, also for biobank services no message is shown, for Diagnosis available filter however it works.

### PR DESCRIPTION
**Pull request by chinook25**
fixes the diagnosis filter part of #3597 

What are the main changes you did:
- added the because you searched for message when applying split ontology filters (e.g. diagnosis available).

how to test:
- see issue

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by esthervanenckevort — APPROVED** [review]
Nice that you cleaned up the code a bit at the same time.
Functionally it seems to work, and the diagnosis filter is indeed not blocking a long time, so that is acceptable.
I was wondering if we could add some tests for this, and Dieuwke should also first approve this after testing the functionality.

**Review by esthervanenckevort — COMMENTED** [review]
If I add a filter for U07.1 COVID-19 Virus identified I see that collections get tagged and then the filtering fires and I see the spinner for a short while. After that the updated results are show, so it looks like it is still firing twice. 🤔

**Comment by chinook25** [comment]
> it is still firing twice

Ye, I just optimized the process by not looping over the ontology anymore and use a hashmap instead, which is way faster. I suggest not fixing the the double application since we want to rewrite the filters to me local, which will make fixing it a lot more easy.

**Comment by esthervanenckevort** [comment]
> > it is still firing twice
> 
> Ye, I just optimized the process by not looping over the ontology anymore and use a hashmap instead, which is way faster. I suggest not fixing the the double application since we want to rewrite the filters to me local, which will make fixing it a lot more easy.

That's fine. Can you then create an issue that describes what has to be done, so we remember to do it after the rewrite of the filters?

**Review by dtroelofsprins — APPROVED** [review]
Functional test:
- Because you searched for is now also shown when using the diagnosis filter and with the latest changes in case of multiple filter options only the matching ones are shown.
- Also tested this filter in combination with other filters, and in that case also the because you searched for works fine (although I came across another (unrelated) bug).

**Pull request merged**
