### PR TITLE
fix: rdf export should produce IRIs for composite keys

### PR DESCRIPTION
**Pull request by mswertz**
see composite key test
bottomline, composite keys will be composed to uri like `http://localhost/schema/table/persons/firstName=Bofke&lastName=de%20Vries`

Importantly, I refactored from using `retrieveJSON` to `retrieveRows` so we can make use of Row.getXXX typed calls and having all elements of composite (foreign) keys included in the row without effort (e.g. row(patient.firstName=Bofke...))

### CODE REVIEW

**Review by esthervanenckevort — CHANGES_REQUESTED** [review]
General code looks fine, but there are still some issues:
- Code crash on ValueToRDF.java line 170 with the FAIR Data Hub example. RDF export failed due to an exception: begin 0, end 19, length 16. We should not use toString() but a proper formatting function
- Some code smells that should be addressed and can make the code more readable (see reports)
- schemaRdfApiContext in RDFService is created without the port (should be there if it is not the well-known port for the protocol)

**Comment by mswertz** [comment]
> * schemaRdfApiContext in RDFService is created without the port (should be there if it is not the well-known port for the protocol)

So this bit of code looks okay so somewhere else it must be wrong?
image

**Comment by mswertz** [comment]
> DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss")

done

**Comment by esthervanenckevort** [comment]
> > * schemaRdfApiContext in RDFService is created without the port (should be there if it is not the well-known port for the protocol)
> 
> So this bit of code looks okay so somewhere else it must be wrong? image
> 
> And tests look also okay image
> 
> Or do you mean the 'path' might be removed?

I think I might have been mistaken, reading host as just the hostname. Probably it would be better to call that baseURL, since that better reflects what it is.

**Review by esthervanenckevort — APPROVED** [review]
I suggest to postpone fixing the last two code smell reported since they should not be part of the semantics package.

**Pull request merged**
