### PR TITLE
feat: in molgenis.csv using oldName and drop to rename/drop columns and/or tables

### PR DESCRIPTION
**Pull request by mswertz**
See the changes to documentation on how this works.

This is existing functionality that was already used via graphql to power the schema editor (where renaming/dropping is normal).

The new feature is that you can also now use the molgenis.csv to enable rename/drop migrations.

### CODE REVIEW

**Comment by mswertz** [comment]
[Feat: enable oldname/newname via molgenis.csv](https://trello.com/c/jtSBzo9B/576-feat-enable-oldname-newname-via-molgeniscsv)

**Review by erikzwart — CHANGES_REQUESTED** [review]
I loaded the PET_STORE template and test data, deleting a column User.phone worked.
Renaming the table Category to Type did not. Got an getRefTable error see screenshot. Also included the molgenis.csv
getRefTable

[molgenis.zip](https://github.com/molgenis/molgenis-emx2/files/10029620/molgenis.zip)

**Comment by mswertz** [comment]
[feat: in molgenis.csv using oldName and drop to rename/drop columns and/or tables](https://trello.com/c/mQJG3lmY/586-feat-in-molgeniscsv-using-oldname-and-drop-to-rename-drop-columns-and-or-tables)

**Comment by erikzwart** [comment]
Used the same example (petstore) as above and now the table Category is correctly renamed to type.
petstore
[molgenis.zip](https://github.com/molgenis/molgenis-emx2/files/10352085/molgenis.zip)

**Review by erikzwart — APPROVED** [review]

**Pull request merged**
