### PR TITLE
fix: java21 build support

### PR DESCRIPTION
**Pull request by svandenhoek**
### how to test:
- Validate if it can be build correctly using Java17 & Java21 ("it worked on my machine" n>1)
  - Set `$JAVA_HOME` and run `./gradlew run`

### todo:
- [ ] updated docs in case of new feature -> Consider adding a `requirements` page in docs with exact details instead of info being scattered in the documentation?
- [ ] added tests
- [ ] updated testplan to include a test for this fix, including ref to bug using # notation

### Changelog:
* Updated google-java-format to v1.22.0 due to error building in Java21:
  > You are running Spotless on JVM 21. This requires google-java-format of at least 1.17.0 (you are using 1.15.0).
* Moved `targetCompatibility`/`sourceCompatibility` from the root `build.gradle` to `apps/build.gradle` due to the following error:
  > emx2:main: Could not resolve project :apps
* Java version is now stored inside a single variable in the root instead of hardcoded in multiple locations (`rootProject.ext.javaVersion`).
* The non-gradle file changes were done automatically due to the updated google-java-format.

### Failed tests (local run through IntelliJ IDEA)
* TestScriptTask -> testPython(): `AssertionFailedError`
* WebApiSmokeTests:
  When testing everything in the project using jUnit, it gives the following error:
`java.lang.reflect.InaccessibleObjectException: Unable to make field final java.util.Map java.util.Collections$UnmodifiableMap.m accessible: module java.base does not "opens java.util" to unnamed module @3d680b5a`
  However, when running `WebApiSmokeTests.java` directly (which uses a Gradle config instead of jUnit), 4 are skipped and 1 fails with `AssertionFailedError`

In both cases, the `AssertionFailedError` was present already in the master (didn't run all tests on the master, only the ones failed in the branch). Additionally, several tests in the branch were ignored by IDEA.

### CODE REVIEW

**Comment by svandenhoek** [comment]
> ## [Quality Gate Failed](https://sonarcloud.io/dashboard?id=molgenis_molgenis-emx2&pullRequest=3602) **Quality Gate failed**
> 
> Failed conditions  [65.0% Coverage on New Code](https://sonarcloud.io/component_measures?id=molgenis_molgenis-emx2&pullRequest=3602&metric=new_coverage&view=list) (required ≥ 80%)
> 
> [See analysis details on SonarCloud](https://sonarcloud.io/dashboard?id=molgenis_molgenis-emx2&pullRequest=3602)

As any changes to non-graddle files are purely automated formatting changes, this error should not matter.

**Review by harmbrugge — APPROVED** [review]
Using java 17 & 21 also works for me. So nice improvement.

**Comment by svandenhoek** [comment]
PR could cause some merge conflicts after merging as long as people work on outdated copies of master due to formatting changes caused by new version of google code formatter.

**Comment by svandenhoek** [comment]
Only coverage fails, though as this is caused by formatting changes, merging PR.

**Pull request merged**
