### PR TITLE
chore: Add cohort metadata staging area model

### PR DESCRIPTION
**Pull request by connoratrug**
- Stripped down version of catalogue model to be used as staging area
- Refers to 'UMCG' Schema for shared resources

note unsure if this should be part of EMX2 repository, if not maybe move to https://github.com/molgenis/molgenis-py-cohorts-etl and include version number to keep models in sync

### CODE REVIEW

**Comment by mswertz** [comment]
Thx, will review. And regarding your question I have reverse question, should python scrip t not be merged into this repo? :-)

**Comment by mswertz** [comment]
Why did you copy model? Would ‘extendTable’ for each of the tables not suffice? Eg ‘MyCohort extends Cohort’? Potential drawback is that data template would differ. Advantage is that data is integrated from start?

**Comment by connoratrug** [comment]
> Thx, will review. And regarding your question I have reverse question, should python scrip t not be merged into this repo? :-)

script has version, there can only be one (github)release per repo, could sync script version with repo but that would result in a new docker image ( for the script ) each time the emx2 is released. Single repo creates multiple artefacts. Technically not an issue, but lost of artefacts would have the same bytes with different version numbers.

**Comment by mswertz** [comment]
Like to discuss this repo stuff in more depth at some point. Is not urgent to me so doesnt block this pull request in my mind. Bytes are cheap, version conflicts expensive. Discussion is broader because could consider ‘catalogue’ as the thing needing a version (separate of emx2)

**Comment by mswertz** [comment]
On another topic: I think this pull request should not be perceived as umcg specific. This is a recurring theme. In this case for cohorts to add metadata, but similarly we should have similar templates for datasources/databanks.

**Comment by connoratrug** [comment]
> think this pull request should not be perceived as umcg specific.

I agree , the problem is that this PR is schema (umcg) specific, due to the need to reference a catalogue schema in the staging schema. For now i would argue to move this pr to a project specific repo and add a story that removes the need for a separate staging area schema

**Comment by connoratrug** [comment]
close in favour of https://github.com/molgenis/molgenis-py-cohorts-etl/pull/3

**Pull request closed without merging**
