### PR TITLE
feat: Update catalogue model

### PR DESCRIPTION
**Pull request by connoratrug**
Change Cohort.designDescription from String to Text type

setup for running migrations to update servers

### CODE REVIEW

**Comment by mswertz** [comment]
I am trying to understand why you would want to use Python for this? The other migrations we do in Java?

**Comment by connoratrug** [comment]
> I am trying to understand why you would want to use Python for this? The other migrations we do in Java + SQL. Seems to be much more direct, faster and most importantly can run in a transaction.

1) To allow contributors without java/sql knowledge to write migrations and (re)use the molgenis api to enable the molgenis system to keep meta data in sync and check permissions. 
2) Not sure running via java would be faster ( most of the work is db work not function calls )
3) Not sure large migrations are going to be able to remain transactional.

**Comment by connoratrug** [comment]
[Write migration to deploy catalogue model change to all ( 100 +) staging areas](https://trello.com/c/qH2VWOoM/510-write-migration-to-deploy-catalogue-model-change-to-all-100-staging-areas)

**Comment by connoratrug** [comment]
close in favour of server side migrations that can run inside a transaction

**Pull request closed without merging**
