### PR TITLE
feat: improve usability OntologyInput

### PR DESCRIPTION
**Pull request by mswertz**
Changed OntologyInput to make search look less invasive.

I can be shown as a 'pulldown' and  just as 'checkboxes'. Now the default is 'pulldown'.

Please advice what version you like for (a) forms (MS: I think the select version) and (b) for table explorer (MS: unsure).

To test component in styleguide here
https://preview-pr-emx2-816.dev.molgenis.org/apps/styleguide/#!/InputOntology 

To test in real live upload a download from data-catalogue and e.g. inspect AreasOfInformation

### CODE REVIEW

**Comment by mswertz** [comment]
[feat: improve ux of ontology input so the search box is less distracting](https://trello.com/c/VBI2tOms/352-feat-improve-ux-of-ontology-input-so-the-search-box-is-less-distracting)

**Comment by BrendaHijmans** [comment]
-Can find 681 out of 812 variables from the topic tree. This is correct, 681 variables have a keyword. 
-This does not include the repeats, repeats are only mentioned in the variable details. For LifeCycle purposes we may need to change this (but is a new story).
-The search bar is not easily recognized as a search bar, maybe include a pictogram and/or lining?
-Selection of notes works well.

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
-Can find 681 out of 812 variables from the topic tree. This is correct, 681 variables have a keyword.
-This does not include the repeats, repeats are only mentioned in the variable details. For LifeCycle purposes we may need to change this (but is a new story).
-The search bar is not easily recognized as a search bar, maybe include a pictogram and/or lining?
-Selection of nodes works well.

**Comment by mswertz** [comment]
> -Can find 681 out of 812 variables from the topic tree. This is correct, 681 variables have a keyword.
> -This does not include the repeats, repeats are only mentioned in the variable details. For LifeCycle purposes we may need to change this (but is a new story).
> -The search bar is not easily recognized as a search bar, maybe include a pictogram and/or lining?
> -Selection of nodes works well.

Thank you. What changes do you exactly request? Adding a pictogram to the search? 
And I see a feature request specific to use in context of variable explorer on repeated vars which makes sense but is indeed outside scope for this PR

**Review by BrendaHijmans — APPROVED** [review]

**Pull request merged**
