### PR TITLE
feat: Add docs links

### PR DESCRIPTION
**Pull request by connoratrug**
What are the main changes you did:
- Just added the links, need to discuss if we want to combine 'upload' with 'docs' links ( if zo how to we call this new link)
- Think about adding links / other stuff to footer

how to test:
- click the links 

todo:
- [ ] updated docs in case of new feature
- [ ] added/updated tests
- [ ] added/updated testplan to include a test for this fix, including ref to bug using # notation

### CODE REVIEW

**Review by mswertz — APPROVED** [review]

**Comment by EleanorHyde-UMCG** [comment]
> maybe open in new tab would be better , and maybe hide in cohortOnly context

I agree that opening 'upload data' and 'manual' in a new tab each time would be more user-friendly. Not sure what you mean by cohortOnly, though?

**Comment by EleanorHyde-UMCG** [comment]
@marijevdgeest have you seen this yet? Does this match your spec?

**Comment by EleanorHyde-UMCG** [comment]
Nice. Please could you change the text to 'Manuals' (meervoud)?  @connoratrug 

We need to discuss later where we want the 'about' information. I'll make a separate story for that (the manuals are currently more important). But if the text is changed to 'Manuals' I'm happy. Thanks.

**Review by EleanorHyde-UMCG — CHANGES_REQUESTED** [review]
Nice. Please could you change the text to 'Manuals' (meervoud)? @connoratrug

We need to discuss later where we want the 'about' information. I'll make a separate story for that (the manuals are currently more important). But if the text is changed to 'Manuals' I'm happy. Thanks.

**Pull request merged**
