### PR TITLE
feat[catalogue]: added meta data items for databanks and datasources. Depends on #502

### PR DESCRIPTION
**Pull request by mswertz**
Adds all changes from Minerva and UMCG catalogue project.
Also merges https://github.com/molgenis/molgenis-emx2/pull/502 so please review and merge that one first.

This pull request contains changes in 'data' (mainly example data files that we converted from Excel to csv which makes this pull request huge) and a few vuejs changes to make user interface comply.

### CODE REVIEW

**Comment by mswertz** [comment]
I don't understand why this now breaks, seems to be difference between 'mac' and 'linux'.

**Comment by mswertz** [comment]
[Feat: can add 'header' into your forms.](https://trello.com/c/xoyfUZoX/231-feat-can-add-header-into-your-forms)

**Review by BrendaHijmans — COMMENTED** [review]
slight changes to model in commit: https://github.com/molgenis/molgenis-emx2/pull/460/commits/cca4cc8a3a9083623855e26cb8a74603af370077

**Comment by BrendaHijmans** [comment]
Intsitutions detail view has a wrong reference in it:
image

**Review by connoratrug — APPROVED** [review]

**Pull request merged**
