### PR TITLE
feat: add basic sorting

### PR DESCRIPTION
**Pull request by mswertz**
To test: click on column on table explorer; then it should sort.

Todo: 
[x] unit test
[x] refback fixed
[x] url fixed

On purpose didn't yet start sorting ref_array and refback to ref_array (i.e. lists of values in one cell).
That will be a future feature request I expect.

### CODE REVIEW

**Comment by mswertz** [comment]
[#8419 When viewing a table I want to set 'sort by column' so I can find my rows more easily](https://trello.com/c/BaT12O74/335-8419-when-viewing-a-table-i-want-to-set-sort-by-column-so-i-can-find-my-rows-more-easily)

**Review by connoratrug — CHANGES_REQUESTED** [review]
please remove the debug code , suggest not adding it and using the vue inspecto
Screenshot 2021-12-02 at 19 59 50
r

**Comment by mswertz** [comment]
pff, thx for spotting. Was ticktocking with the debug.

**Comment by connoratrug** [comment]
> .. it and using the vue inspecto 

'inspecto vue' :D , inspector

**Review by connoratrug — APPROVED** [review]
ux could be improved by adding an 'on hover' to the column header that shows that there is the option to sort the rows ( see data-explorer 2 as an example)

**Pull request merged**
