### PR TITLE
fix: default of table explorer to be 'canView'

### PR DESCRIPTION
**Pull request by mswertz**
We have issue that we now can disable 'canView' to accomodate when user has 'aggregate' permission only. But default was 'false' which lead to random errors in other places using the table explorer. With this fix we disable that, however we must make sure this doesn't lead to errors in case user has only aggregate.

### CODE REVIEW

**Review by dtroelofsprins — COMMENTED** [review]
I've checked https://preview-emx2-pr-2770.dev.molgenis.org/_SYSTEM_/tasks/#/scripts, but it seems still to be broken.

**Comment by mswertz** [comment]
> I've checked https://preview-emx2-pr-2770.dev.molgenis.org/_SYSTEM_/tasks/#/scripts, but it seems still to be broken.

Thank you. Next time I would be happy that you then mark this PR with 'changes requested' using the review tab ;-)

**Review by dtroelofsprins — CHANGES_REQUESTED** [review]
Sorry, I indeed used the review tab, only forgot to pick the right "request for change" option.

**Comment by connoratrug** [comment]
i f*****up the merge but  think add the same change to default in the wrapping component should fix the issue, ill wait for CI to test on

**Review by dtroelofsprins — APPROVED** [review]
Yes, in the preview the TableExplorer view for scripts and jobs is back again!

**Pull request merged**
