### PR TITLE
Feat/components explorer table

### PR DESCRIPTION
**Pull request by connoratrug**
Move table explorer 

todo
- [x] fetch meta and data 
- [x] columns
- [x] table view
- [x] wire filters
- [x] wire settings
- [x] wire card view
- [x] wire list view
- [x] wire edit btns
- [x] style
- [x] truncate table action
- [x] card button action
- [x]  fix pagination
- [x] check truncate

### CODE REVIEW

**Review by MaxPostema — CHANGES_REQUESTED** [review]
- Do we think its worth it having two ( simple wrappers ) that are the same expect for a class definition?
See: RecordCard.vue  / tableCards.vue
By the way:  Why is one called “Card” and the other one “Cards“ if they both use a "v-for”?

- I know its just moved, but a lot of new components don’t have demo’s :’(

- ConfirmModal: The used default buttons are a bit ugly. My first thought was is the styling missing or something was broken.

- The filters “mg_insertedOn, mg_updatedBy, mg_updatedOn” seem to give errors when being added, other behavior then in styleguide.
“index.cd7eccfc.js:911 [Vue warn]: Invalid prop: custom validator check failed for prop "columnType".”

- Is it correct that the cardTemplate/recordTemplate Is broken in both molgenis-components and styleguide? I can set “<b>hallo world</b>” but ”<b>{{name}}</b>“ is broken.

**Review by MaxPostema — CHANGES_REQUESTED** [review]
Pagination of the explorertable works on styleguide but not on molgenis-components

**Review by MaxPostema — CHANGES_REQUESTED** [review]
The truncate button is not working.

**Comment by connoratrug** [comment]
tested ssr docker build for this PR , ssr 'works' ( no errors on including the lib)

**Pull request merged**
