### PR TITLE
build: upgrade circleci to postgresql 15

### PR DESCRIPTION
**Pull request by mswertz**

### CODE REVIEW

**Review by connoratrug — COMMENTED** [review]
add check to system startup for 'supported' postgres version, if version is not supported the logs should include a warning ( or exit with clear error msg)

**Comment by mswertz** [comment]
> add check to system startup for 'supported' postgres version, if version is not supported the logs should include a warning ( or exit with clear error msg)

But if the tests pass it should work right?

**Comment by mswertz** [comment]
> > > add check to system startup for 'supported' postgres version, if version is not supported the logs should include a warning ( or exit with clear error msg)
> > 
> > 
> > But if the tests pass it should work right?
> 
> for 15 , but what about 14 ( or 16 , 12 , or .....), ie it should check for supported versions

Hmm, I thought we should only support one version? otherwise we should in my mind add more tests? I.e. to also test against other versions?

**Comment by mswertz** [comment]
Alternatively we could add a test against https://www.jooq.org/javadoc/3.19.x/org.jooq/org/jooq/SQLDialect.html#POSTGRES
And then if this fails the message that we should update test and manual?

**Comment by connoratrug** [comment]
> > > > add check to system startup for 'supported' postgres version, if version is not supported the logs should include a warning ( or exit with clear error msg)
> > > 
> > > 
> > > But if the tests pass it should work right?
> > 
> > 
> > for 15 , but what about 14 ( or 16 , 12 , or .....), ie it should check for supported versions
> 
> Hmm, I thought we should only support one version? otherwise we should in my mind add more tests? I.e. to also test against other versions?

exactly; therefore if we now only test using 15 ( instead of 14 ) we should show a warning ( or exit ) when a user connects to a different version , small check i would guess. 

This also does not yet explain the issue some users have experienced with initing the system on pg 15

**Review by connoratrug — APPROVED** [review]

**Comment by mswertz** [comment]
> exactly; therefore if we now only test using 15 ( instead of 14 ) we should show a warning ( or exit ) when a user connects to a different version , small check i would guess.

Ah, good point. Will create a story.

**Pull request merged**
