### PR TITLE
fix: center page header title

### PR DESCRIPTION
**Pull request by connoratrug**

### CODE REVIEW

**Review by mswertz — COMMENTED** [review]
Looks weird in case of cohorts; there you would somehow expect title to center above the content (so not including the left side menu). Now it looks 'off' center somehow LOL. How did designer do this?

**Comment by mswertz** [comment]
It is not too bad, but if you have menu on the left then having title centered makes it looks offcenter because somehow my eye is focussed on right panel and I expect title to be on top of that 
image

**Comment by connoratrug** [comment]
> It is not too bad, but if you have menu on the left then having title centered makes it looks offcenter because somehow my eye is focussed on right panel and I expect title to be on top of that 

I see what you mean, i suggest to take a look at the design files ( figma) here can see that for the list/search page the title is meant to be centered over the right column and for the details page its meant to be centered across both columns.

**Comment by connoratrug** [comment]
fixed in other context

**Pull request closed without merging**
