### PR TITLE
feat: Split up cohort view general design into two sections: General …

### LINKED ISSUE #3609: Split up cohort view general design into two sections: General design and Population and add some missing data items
**What version of EMX2 are you using (see footer)**
v10.49.10

**Describe the bug**
Some data items for cohorts are not shown. 

**To Reproduce**
1. Go to https://emx2.dev.molgenis.org/catalogue-demo/ssr-catalogue/testNetwork1/cohorts/testCohort1
2. Scroll down to section General design.
3. The section can be subdivided into 2 sections as such:

“General design”, with fields: 
Cohort type
Design
Design description
Design schematic
Collection type
Start/end year
Design paper
PID

"Population", with fields: 
Countries (renamed from Population, does not cover the content)
Regions
Number of participants
Number of participants with samples
Population age groups
Main medical condition
_ICDO site (Data resources.population oncology topology; ontology_array)
ICDO morphology (Data resources.population oncology morphology; ontology_array)
Inclusion criteria (Cohorts.inclusion criteria; ontology_array)
Other inclusion criteria (Cohorts.other inclusion criteria; text)_

New fields in italics

image

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

### PR DESCRIPTION
**Pull request by connoratrug**
…design and Population and add some missing data items

Closes #3609

see issue

### CODE REVIEW

**Review by mswertz — COMMENTED** [review]
code looks good @BrendaHijmans  please approve after functional review.

P.S. I notice that if there are ontoogies without nesting then we get a lot of empty space (to hold the arrow down that is not there). Would that be something to fix? I.e. that we don't indent when there is no reason? Or that we introduce another icon for items that have no children? 

image

**Comment by connoratrug** [comment]
> code looks good @BrendaHijmans please approve after functional review.
> 
> P.S. I notice that if there are ontoogies without nesting then we get a lot of empty space (to hold the arrow down that is not there). Would that be something to fix? I.e. that we don't indent when there is no reason? Or that we introduce another icon for items that have no children?
> 
> image

Yes i noticed, this is actually a bit tricky , as sometimes the tree is used in a larger list where you would like the items to left-align, suggest to handle this an a separate issue, we could add a prop to render the tree as list if max-depth = 1 , but then you would need to check all tree use cases to see if it should do this

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
Can you put 'Population' into a separate panel? It seems inconsistent to keep two headings in one panel.

As described in #3609, can you name 'Population oncology topology' 'ICDO site' and cab you name 'Population oncology morphology' 'ICDO morphology'?

**Comment by EleanorHyde-UMCG** [comment]
> Can you put 'Population' into a separate panel? It seems inconsistent to keep two headings in one panel.
> 
> As described in #3609, can you name 'Population oncology topology' 'ICDO site' and cab you name 'Population oncology morphology' 'ICDO morphology'?
> 
> Can you rename 'Age group at inclusion' to 'Poplation age groups'? This was agreed upon by Eleanor and Kim.

In addition to what Brenda added above, could you also please do the following as well?

- check you've not accidentally removed the "Design schematic" field - I can't see it currently in dev and this may be a data issue, but in acc it should still be visible
- add the 'Publications' field under the Design paper field
- add the following fields under 'Access Conditions':
- - Release type
- - Linkage possibility description
- - Data access fee
- - Prelinked
- - Data holder
- - Data use conditions

Thanks!

**Comment by connoratrug** [comment]
> > Can you put 'Population' into a separate panel? It seems inconsistent to keep two headings in one panel.
> > As described in #3609, can you name 'Population oncology topology' 'ICDO site' and cab you name 'Population oncology morphology' 'ICDO morphology'?
> > Can you rename 'Age group at inclusion' to 'Poplation age groups'? This was agreed upon by Eleanor and Kim.
> 
> In addition to what Brenda added above, could you also please do the following as well?
> 
> * check you've not accidentally removed the "Design schematic" field - I can't see it currently in dev and this may be a data issue, but in acc it should still be visible
> * add the 'Publications' field under the Design paper field
> * add 'Population disease' under 'Main medical condition'
> * add the following fields under 'Access Conditions':
> * * Release type
> * * Linkage possibility description
> * * Data access fee
> * * Prelinked
> * * Data holder
> * * Data use conditions
> 
> Thanks!

These are all new requests or requests related to other tickets, please limit the review to feature and code change,

Thanks !

**Comment by BrendaHijmans** [comment]
> > > Can you put 'Population' into a separate panel? It seems inconsistent to keep two headings in one panel.
> > > As described in #3609, can you name 'Population oncology topology' 'ICDO site' and cab you name 'Population oncology morphology' 'ICDO morphology'?
> > > Can you rename 'Age group at inclusion' to 'Poplation age groups'? This was agreed upon by Eleanor and Kim.


My original comments (see above) are related to the feature, please reconsider.

**Pull request merged**
