### PR TITLE
fix: update file input for vue3 use

### LINKED ISSUE #1893: Can't add logo's to cohorts
**What version of EMX2 are you using (see footer)**
[8.134.0](https://github.com/molgenis/molgenis-emx2/releases/tag/v8.134.0)

**Describe the bug**
Can't select a logo in the cohorts tabel

**To Reproduce**
1. Go to '[https://emx2.test.molgenis.org'](https://catalogue-acc.molgeniscloud.org/UMCG_SABRINATEST/tables/#/Cohorts)'
2. Click on edit row
3. Scroll down to 'logo'
4. You can click on logo, a windows opens and you can choose a logo. However, the image won't be selected

**Expected behavior**
Logo added to cohort

### PR DESCRIPTION
**Pull request by connoratrug**
Closes #1893

### CODE REVIEW

**Review by mswertz — APPROVED** [review]

**Review by mswertz — CHANGES_REQUESTED** [review]
I see following when file uploaded
- name is missing
- i think the input should be empty?

image

**Comment by connoratrug** [comment]
> I see following when file uploaded
> 
> * name is missing
> * i think the input should be empty?
> 
> image

I thought the empty input was a bug in the previous version, updated the render to have the same behaviour as the vue2 version

**Review by chinook25 — APPROVED** [review]
👍

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
Functional review: in forms files uploaded to 'design schematic' are not present in the form anymore when reopening a form. References to the file are present in zip download, but not in Excel download. In Excel download the data items (columns) 'design schematic' and 'logo' are not present in the Cohorts sheet at all.

**Comment by connoratrug** [comment]
> Functional review: in forms files uploaded to 'design schematic' are not present in the form anymore when reopening a form. References to the file are present in zip download, but not in Excel download. In Excel download the data items (columns) 'design schematic' and 'logo' are not present in the Cohorts sheet at all.

Can not reproduce; when i use the PR preview to test , i can add a new row ( Petstore.User) row with an image (type = File) and update the image , closing in and reopening the User the image is still there. When i download the table (zip) the image is part of the download. @BrendaHijmans please add exact steps to reproduce and if needed create new issue for exel download ( this PR does not touch any of up / download api code)

**Comment by BrendaHijmans** [comment]
Steps to reproduce:

- in preview make a new schema
- choose data catalogue 3 as template and upload example data = true
- add a cohort in Cohorts table, add images at ‘design schematic’ and ‘logo’.
- save and reopen form (edit). See that at ‘logo’ there is a ‘previous image’, at ‘design schematic’ this is not shown.

**Comment by connoratrug** [comment]
> Steps to reproduce: - in preview make a new schema - choose data catalogue 3 as template and upload example data = true - add a cohort in Cohorts table, add images at ‘design schematic’ and ‘logo’. - save and reopen form (edit). See that at ‘logo’ there is a ‘previous image’, at ‘design schematic’ this is not shown.
> […](#)
> Op 17 jan. 2023 om 10:22 heeft connoratrug ***@***.***> het volgende geschreven: ﻿ Functional review: in forms files uploaded to 'design schematic' are not present in the form anymore when reopening a form. References to the file are present in zip download, but not in Excel download. In Excel download the data items (columns) 'design schematic' and 'logo' are not present in the Cohorts sheet at all. Can not reproduce; when i use the PR preview to test , i can add a new row ( Petstore.User) row with an image (type = File) and update the image , closing in and reopening the User the image is still there. When i download the table (zip) the image is part of the download. @BrendaHijmans please add exact steps to reproduce and if needed create new issue for exel download ( this PR does not touch any of up / download api code) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.

This seems to be a _catalogue3_ issue. using the catalogue(2) i can add the file ( same for pet store and components lib demo). The code in this pr is not related to the catalogue(3). Suggest to open separate issue for catalogue 3 File issue.

**Comment by connoratrug** [comment]
> @connoratrug I will check whether the problem persists in catalogue 3 after you have merged

The PR can only be merged after you and @mswertz accepted the changes

**Review by mswertz — APPROVED** [review]

**Review by BrendaHijmans — APPROVED** [review]

**Pull request merged**
