### PR TITLE
feat: Update catalogue model, rename databanks to cohorts

### PR DESCRIPTION
**Pull request by connoratrug**
IMPORTANT: this is a breaking change on the catalogue data model
after merge the data needs to be loaded into the new model format

Related to: https://github.com/molgenis/molgenis-projects/pull/72

test against: https://emx2.dev.molgenis.org/ schema: `Catalogue_test`

### CODE REVIEW

**Review by mswertz — APPROVED** [review]

**Review by mswertz — CHANGES_REQUESTED** [review]
Hoi, deze explorer moet ook werken voor databanks. Dus zou ik verwachten dat je 'resources' gebruikt ipv Databanks of Cohorts. Waarom gebruik je de specifieke databank/cohort query?

**Comment by connoratrug** [comment]
@mswertz  maar kunnen alle resources ( y as) worden gematched om een variable (x ass) harmonizatie (x, y) ?

**Comment by mswertz** [comment]
> @mswertz maar kunnen alle resources ( y as) worden gematched om een variable (x ass) harmonizatie (x, y) ?

Ja

**Comment by connoratrug** [comment]
[Move lifecycle data from Databank to Cohorts](https://trello.com/c/JoPSWLWh/116-move-lifecycle-data-from-databank-to-cohorts)

**Review by mswertz — APPROVED** [review]
Looks good. Only thing I didn't check if what happens if I have a database with variables of which some are from a Resource=Databank and some other from Resource=Cohort. I believe it will work but didn't test it. So unless you have concerns about it I propose you merge.

**Pull request merged**
