### PR TITLE
chore: update testplans

### PR DESCRIPTION
**Pull request by marijevdgeest**
Update testplans after first test cycle

### CODE REVIEW

**Review by EleanorHyde-UMCG — APPROVED** [review]

**Review by erikzwart — APPROVED** [review]

**Review by timcadman — COMMENTED** [review]
Step 26: I do not see 'EUROCAT NNL' - no data sources are shown

**Review by timcadman — COMMENTED** [review]
We had a debate about whether to include the github issue in the test plan - was the final decision to include?

**Review by timcadman — COMMENTED** [review]
I'm unsure of the exact purpose of this test. Was it meant to be a 'catch all' to include all bugs we found and want checked in future testing? If so then this could be more clearly specified (and more steps added). If not could you clarify the goal?

**Comment by EleanorHyde-UMCG** [comment]
> We had a debate about whether to include the github issue in the test plan - was the final decision to include?

I think we decided not to use it here. To be consistent we should indeed probably remove it...

**Comment by EleanorHyde-UMCG** [comment]
> I'm unsure of the exact purpose of this test. Was it meant to be a 'catch all' to include all bugs we found and want checked in future testing? If so then this could be more clearly specified (and more steps added). If not could you clarify the goal?

Not sure which testplan you meant here? Testplan 10 is meant as a testplan for someone at GCC to use to check "random" (as in, unrelated) things which require a larger testset than what we currently have set up. (eg paging through to page 2 of a list of cohorts  / checking that long variable names get displayed properly etc etc). But did you mean another testplan (sorry, I can't see where the comment is attached to)?

**Comment by EleanorHyde-UMCG** [comment]
> Step 26: I do not see 'EUROCAT NNL' - no data sources are shown

Interesting, I don't either now. EUROCAT NNL is production data and therefore easily changed. Thanks for this - we should make a test data source and use that here instead.

**Comment by timcadman** [comment]
> > I'm unsure of the exact purpose of this test. Was it meant to be a 'catch all' to include all bugs we found and want checked in future testing? If so then this could be more clearly specified (and more steps added). If not could you clarify the goal?
> 
> Not sure which testplan you meant here? Testplan 10 is meant as a testplan for someone at GCC to use to check "random" (as in, unrelated) things which require a larger testset than what we currently have set up. (eg paging through to page 2 of a list of cohorts / checking that long variable names get displayed properly etc etc). But did you mean another testplan (sorry, I can't see where the comment is attached to)?

Sorry yes - I meant test plan 10

**Comment by EleanorHyde-UMCG** [comment]
> > > I'm unsure of the exact purpose of this test. Was it meant to be a 'catch all' to include all bugs we found and want checked in future testing? If so then this could be more clearly specified (and more steps added). If not could you clarify the goal?
> > 
> > 
> > Not sure which testplan you meant here? Testplan 10 is meant as a testplan for someone at GCC to use to check "random" (as in, unrelated) things which require a larger testset than what we currently have set up. (eg paging through to page 2 of a list of cohorts / checking that long variable names get displayed properly etc etc). But did you mean another testplan (sorry, I can't see where the comment is attached to)?
> 
> Sorry yes - I meant test plan 10

OK thanks, will adjust the goal text

**Pull request merged**
