### PR TITLE
feat: ssr harmonization details

### PR DESCRIPTION
**Pull request by connoratrug**
Show variable harmonization details

### CODE REVIEW

**Review by BrendaHijmans — COMMENTED** [review]
The networks filter is referring to Organisations, not Networks

**Review by BrendaHijmans — COMMENTED** [review]
The search box says 'search cohorts', this is not correct, since you are searching in the variables.

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
The symbols of 'harmonisation status per cohort' are not correct: complete should have the green check-sign, partial should have the % sign, no data should be empty:
image
image

**Review by BrendaHijmans — COMMENTED** [review]
Within the MOLGENIS platform we have decided to use British English spelling, so we should use harmonisation (with an 's').

**Review by BrendaHijmans — CHANGES_REQUESTED** [review]
Cannot see beyond the cohorts starting with an 'R'. There should be more cohorts here (e.g. Sepages, SWS...
image

**Comment by connoratrug** [comment]
> Within the MOLGENIS platform we have decided to use British English spelling, so we should use harmonisation (with an 's').

😢 harmonisation hurts my eyes

**Comment by EleanorHyde-UMCG** [comment]
Harmonization status per cohort laat niet alle cohorten zien:
image

Deze stopt bij LSC terwijl in het overzicht eronder onder Harmonization details per cohort kan ik helemaal doorscrollen naar nog 21 andere cohorten na LSC.

image

**Comment by EleanorHyde-UMCG** [comment]
The filters on the left hand side are fixed scroll-wise to the results on the right hand side, which means you have to keep scrolling up and down if you want to see the results of what you've chosen at (eg) the bottom of the list of cohorts to filter on. It would be easier for the user if you could scroll filters on the left and contents on the right with separate scroll bars.

image
image
image
image
image

**Comment by EleanorHyde-UMCG** [comment]
This is most likely a data issue but still interesting: there are variables in the list which apparently aren't linked to any cohort or any network whatsoever - do we want this to be able to happen? Should we be making it compulsory for a variable to be linked to at least one cohort or network or both? eg search on "m_bps" and filter on no cohorts or networks and you get this:
image
image

I then tried to find out which cohort or network these variables were linked to and ended selecting all cohorts and networks (!) and still got no results:
image

This wouldn't happen in production but do we want to stop it being able to happen?

**Comment by EleanorHyde-UMCG** [comment]
I went to the Athlete variables page (https://preview-emx2-pr-2905.dev.molgenis.org/catalogue-demo/ssr-catalogue/networks/ATHLETE#variables) and noticed a couple of things, but perhaps this is still in development:
- I can't see how many variables there are in the catalogue for Athlete
- I can't filter on the variables anywhere (unlike above), is this as designed?  eg if I wanted to do the same filter I did as above (search on "m_bps") I would have to click through the alphabetical list (109 pages if I wanted something beginning with Z) until I got to the letter M to go and find it. 

Apologies if I wasn't supposed to go looking here yet ;-)

**Comment by BrendaHijmans** [comment]
The issue here is that the filters are not working yet. All variables are connected to networks/cohorts/databanks.Op 6 nov. 2023 om 16:42 heeft EleanorHyde-UMCG ***@***.***> het volgende geschreven:﻿
This is most likely a data issue but still interesting: there are variables in the list which apparently aren't linked to any cohort or any network whatsoever - do we want this to be able to happen? Should we be making it compulsory for a variable to be linked to at least one cohort or network or both? eg search on "m_bps" and filter on no cohorts or networks and you get this:


I then tried to find out which cohort or network these variables were linked to and ended selecting all cohorts and networks (!) and still got no results:

This wouldn't happen in production but do we want to stop it being able to happen?

**Pull request merged**
